/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Watchlist */
        get: operations["get_watchlist_api_watchlist_get"];
        put?: never;
        /** Post Watchlist */
        post: operations["post_watchlist_api_watchlist_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlist/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Watchlist */
        delete: operations["delete_watchlist_api_watchlist__ticker__delete"];
        options?: never;
        head?: never;
        /** Patch Watchlist */
        patch: operations["patch_watchlist_api_watchlist__ticker__patch"];
        trace?: never;
    };
    "/api/stock/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stock */
        get: operations["get_stock_api_stock__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stock/{ticker}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stock History
         * @description Daily rollup for the Market Structure tab's history table.
         *
         *     One row per trading day, sorted newest-first. Today's row may have
         *     spot=None if the post-close OHLC pull hasn't fired yet.
         */
        get: operations["get_stock_history_api_stock__ticker__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stock/{ticker}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_stock__ticker__runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stock/{ticker}/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Specific Run */
        get: operations["get_specific_run_api_stock__ticker__runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ohlc/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ohlc */
        get: operations["get_ohlc_api_ohlc__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlist/{ticker}/rescan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enqueue Rescan */
        post: operations["enqueue_rescan_api_watchlist__ticker__rescan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlist/rescan-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enqueue Rescan All
         * @description Enqueue a rescan job for every active watchlist ticker.
         */
        post: operations["enqueue_rescan_all_api_watchlist_rescan_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stock/{ticker}/volatility/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Volatility Series */
        get: operations["get_volatility_series_api_stock__ticker__volatility_series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DivergencePoint */
        DivergencePoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Iv Z */
            iv_z?: string | null;
            /** Rv Z */
            rv_z?: string | null;
        };
        /** FlowAlert */
        FlowAlert: {
            /** Id */
            id: string;
            /** Ticker */
            ticker: string;
            /** Option Chain */
            option_chain?: string | null;
            /** Type */
            type?: string | null;
            /** Expiry */
            expiry?: string | null;
            /** Strike */
            strike?: string | null;
            /** Price */
            price?: string | null;
            /** Underlying Price */
            underlying_price?: string | null;
            /** Total Size */
            total_size?: number | null;
            /** Total Premium */
            total_premium?: string | null;
            /** Total Ask Side Prem */
            total_ask_side_prem?: string | null;
            /** Total Bid Side Prem */
            total_bid_side_prem?: string | null;
            /** Volume */
            volume?: number | null;
            /** Open Interest */
            open_interest?: number | null;
            /** Volume Oi Ratio */
            volume_oi_ratio?: string | null;
            /** Has Sweep */
            has_sweep?: boolean | null;
            /** Has Floor */
            has_floor?: boolean | null;
            /** Has Multileg */
            has_multileg?: boolean | null;
            /** All Opening Trades */
            all_opening_trades?: boolean | null;
            /** Iv Start */
            iv_start?: string | null;
            /** Iv End */
            iv_end?: string | null;
            /** Alert Rule */
            alert_rule?: string | null;
            /** Rule Id */
            rule_id?: string | null;
            /** Sector */
            sector?: string | null;
            /** Issue Type */
            issue_type?: string | null;
            /** Next Earnings Date */
            next_earnings_date?: string | null;
            /** Created At */
            created_at?: string | null;
        };
        /** FlowSnapshot */
        FlowSnapshot: {
            /** Ticker */
            ticker: string;
            /** Flow Count */
            flow_count: number;
            /** Net Premium */
            net_premium: string;
            /** Bull Premium */
            bull_premium: string;
            /** Bear Premium */
            bear_premium: string;
            /** Ask Side Premium */
            ask_side_premium: string;
            /** Bid Side Premium */
            bid_side_premium: string;
            /**
             * Top Alerts
             * @default []
             */
            top_alerts: components["schemas"]["FlowAlert"][];
        };
        /** GammaBlock */
        GammaBlock: {
            /** Flip Distance */
            flip_distance?: string | null;
            /** Flip Price */
            flip_price?: string | null;
            /** Per 1Pct Move */
            per_1pct_move?: string | null;
            /** Max Strike */
            max_strike?: string | null;
            /** Expiring Pct */
            expiring_pct?: string | null;
            /** Expiring Date */
            expiring_date?: string | null;
        };
        /**
         * GexLevel
         * @description One labeled level on the GEX curve (e.g. CALL WALL, PUT WALL, MAX MAGNET).
         *
         *     `gamma_per_dollar` is the per-strike net_gex used as the "$N per $1" sensitivity
         *     figure on the tile — the dollar value of dealer hedging triggered by a $1 move.
         */
        GexLevel: {
            /** Strike */
            strike: string;
            /** Net Gex */
            net_gex?: string | null;
            /** Pct From Spot */
            pct_from_spot?: string | null;
            /** Gamma Per Dollar */
            gamma_per_dollar?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Ok */
            ok: boolean;
            /** Db */
            db: string;
            /** Scheduler Lag Seconds */
            scheduler_lag_seconds?: number | null;
            /** Last Full Scan At */
            last_full_scan_at?: string | null;
            /** Reason */
            reason?: string | null;
            /** Worker Lag Seconds */
            worker_lag_seconds?: number | null;
            /** Watchlist Size */
            watchlist_size?: number | null;
            /**
             * Source
             * @default massive.com
             */
            source: string;
            /** Latency P95 Ms */
            latency_p95_ms?: number | null;
            /** Http 2Xx */
            http_2xx?: number | null;
            /** Http 4Xx */
            http_4xx?: number | null;
            /** Http 5Xx */
            http_5xx?: number | null;
            /** Uw Today */
            uw_today?: number | null;
            /** Cache Hit Pct */
            cache_hit_pct?: number | null;
        };
        /** IvHistogramBin */
        IvHistogramBin: {
            /** Lo */
            lo: string;
            /** Hi */
            hi: string;
            /** Count */
            count: number;
        };
        /** IvHvPoint */
        IvHvPoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Iv */
            iv?: string | null;
            /** Rv */
            rv?: string | null;
        };
        /** IvOfIvPoint */
        IvOfIvPoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Iv */
            iv?: string | null;
            /** Iv Of Iv 20 */
            iv_of_iv_20?: string | null;
        };
        /** IvPercentileDistribution */
        IvPercentileDistribution: {
            /**
             * Bins
             * @default []
             */
            bins: components["schemas"]["IvHistogramBin"][];
            /** Current Iv */
            current_iv?: string | null;
            /** Current Pctile */
            current_pctile?: string | null;
        };
        /** JobStatus */
        JobStatus: {
            /** Job Id */
            job_id: string;
            /** Status */
            status: string;
            /** Run Id */
            run_id?: number | null;
            /** Error */
            error?: string | null;
            /**
             * Requested At
             * Format: date-time
             */
            requested_at: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
        };
        /**
         * MarketAggregates
         * @description Per-ticker aggregate fields sourced from the bulk-screener endpoint.
         *
         *     Populated by pipeline.run_single_stock alongside the existing per-section
         *     sub-models. Feeds the watchlist card POSITIONING and SKEW blocks.
         */
        MarketAggregates: {
            /** Call Oi Total */
            call_oi_total?: number | null;
            /** Put Oi Total */
            put_oi_total?: number | null;
            /** Call Volume Total */
            call_volume_total?: number | null;
            /** Put Volume Total */
            put_volume_total?: number | null;
            /** Call Volume Ask Side */
            call_volume_ask_side?: number | null;
            /** Call Volume Bid Side */
            call_volume_bid_side?: number | null;
            /** Put Volume Ask Side */
            put_volume_ask_side?: number | null;
            /** Put Volume Bid Side */
            put_volume_bid_side?: number | null;
            /** Pcr Oi */
            pcr_oi?: string | null;
            /** Pcr Vol */
            pcr_vol?: string | null;
            /** Iv30D */
            iv30d?: string | null;
        };
        /** MarketStructure */
        MarketStructure: {
            /** Spot */
            spot?: string | null;
            /** Nearest Expiry */
            nearest_expiry?: string | null;
            /** Total Call Gex */
            total_call_gex?: string | null;
            /** Total Put Gex */
            total_put_gex?: string | null;
            /** Net Gex */
            net_gex?: string | null;
            /** Total Call Dex Oi */
            total_call_dex_oi?: string | null;
            /** Total Put Dex Oi */
            total_put_dex_oi?: string | null;
            /** Max Pain */
            max_pain?: string | null;
            /**
             * Top Call Oi Strikes
             * @default []
             */
            top_call_oi_strikes: string[];
            /**
             * Top Put Oi Strikes
             * @default []
             */
            top_put_oi_strikes: string[];
        };
        /**
         * MarketStructureLevels
         * @description Derived strike-level reference points used by the Market Structure tab.
         *
         *     Conventions follow FlashAlpha / SpotGamma:
         *       - gex_flip: lowest strike where running cumulative net_gex flips sign
         *       - call_wall: strike with largest call-side gamma (typically above spot)
         *       - put_wall: strike with largest put-side gamma magnitude (typically below spot)
         *       - max_magnet: strike with largest positive net_gex above spot (pulls price up)
         *       - second_magnet: strike with second-largest positive net_gex above spot
         *       - max_accel: strike with most-negative net_gex below the flip (movement accelerator)
         */
        MarketStructureLevels: {
            gex_flip?: components["schemas"]["GexLevel"] | null;
            call_wall?: components["schemas"]["GexLevel"] | null;
            put_wall?: components["schemas"]["GexLevel"] | null;
            max_magnet?: components["schemas"]["GexLevel"] | null;
            second_magnet?: components["schemas"]["GexLevel"] | null;
            max_accel?: components["schemas"]["GexLevel"] | null;
        };
        /** MaxPainRow */
        MaxPainRow: {
            /**
             * Expiry
             * Format: date
             */
            expiry: string;
            /** Max Pain */
            max_pain?: string | null;
            /** Close */
            close?: string | null;
            /** Open */
            open?: string | null;
            /** Next Upper Strike */
            next_upper_strike?: string | null;
            /** Next Lower Strike */
            next_lower_strike?: string | null;
        };
        /** OhlcRow */
        OhlcRow: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Open */
            open?: string | null;
            /** High */
            high?: string | null;
            /** Low */
            low?: string | null;
            /** Close */
            close: string;
            /** Volume */
            volume?: number | null;
        };
        /** OiChangeRow */
        OiChangeRow: {
            /** Underlying Symbol */
            underlying_symbol: string;
            /** Option Symbol */
            option_symbol: string;
            /** Curr Date */
            curr_date?: string | null;
            /** Last Date */
            last_date?: string | null;
            /** Curr Oi */
            curr_oi?: number | null;
            /** Last Oi */
            last_oi?: number | null;
            /** Oi Diff Plain */
            oi_diff_plain?: number | null;
            /** Oi Change */
            oi_change?: string | null;
            /** Volume */
            volume?: number | null;
            /** Trades */
            trades?: number | null;
            /** Avg Price */
            avg_price?: string | null;
            /** Last Fill */
            last_fill?: string | null;
            /** Days Of Oi Increases */
            days_of_oi_increases?: number | null;
            /** Days Of Vol Greater Than Oi */
            days_of_vol_greater_than_oi?: number | null;
            /** Percentage Of Total */
            percentage_of_total?: string | null;
            /** Rnk */
            rnk?: number | null;
        };
        /** PositioningBlock */
        PositioningBlock: {
            /** Call Oi */
            call_oi?: number | null;
            /** Put Oi */
            put_oi?: number | null;
            /** Pcr Oi */
            pcr_oi?: string | null;
            /** Pcr Vol */
            pcr_vol?: string | null;
            /** Pcr Delta 30D */
            pcr_delta_30d?: string | null;
        };
        /** RegimeQuadrantBlock */
        RegimeQuadrantBlock: {
            /**
             * Points
             * @default []
             */
            points: components["schemas"]["RegimeQuadrantPoint"][];
            latest?: components["schemas"]["RegimeQuadrantLatest"] | null;
        };
        /** RegimeQuadrantLatest */
        RegimeQuadrantLatest: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Rvol Pctile */
            rvol_pctile?: string | null;
            /** Spy Corr 21 */
            spy_corr_21?: string | null;
            /**
             * State
             * @default
             */
            state: string;
        };
        /** RegimeQuadrantPoint */
        RegimeQuadrantPoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Rvol Pctile */
            rvol_pctile?: string | null;
            /** Spy Corr 21 */
            spy_corr_21?: string | null;
        };
        /**
         * ReturnsBlock
         * @description Wire shape: d1 / w1 / d30. No aliases — FastAPI would otherwise serialize
         *     them as JSON keys and break the frontend contract.
         */
        ReturnsBlock: {
            /** D1 */
            d1?: string | null;
            /** W1 */
            w1?: string | null;
            /** D30 */
            d30?: string | null;
        };
        /** RvCorrPoint */
        RvCorrPoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Rv */
            rv?: string | null;
            /** Spy Corr 21 */
            spy_corr_21?: string | null;
        };
        /** SetupBlock */
        SetupBlock: {
            /** Type */
            type?: string | null;
            /** Direction */
            direction?: string | null;
            /** Score */
            score?: string | null;
        };
        /** SetupClassification */
        SetupClassification: {
            /** Setup Type */
            setup_type: string;
            /** Label */
            label: string;
            /** Direction */
            direction: string;
            /** Score */
            score: string;
            /**
             * Confirmations
             * @default []
             */
            confirmations: string[];
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
            /**
             * Notes
             * @default
             */
            notes: string;
        };
        /** ShortDataRow */
        ShortDataRow: {
            /** Symbol */
            symbol: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Name */
            name?: string | null;
            /** Short Shares Available */
            short_shares_available?: number | null;
            /** Fee Rate */
            fee_rate?: string | null;
            /** Rebate Rate */
            rebate_rate?: string | null;
        };
        /** SingleStockReport */
        SingleStockReport: {
            /** Run Id */
            run_id: number;
            /** Ticker */
            ticker: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Short Int Note
             * @default n/a (UW endpoint does not expose %)
             */
            short_int_note: string;
            market_structure: components["schemas"]["MarketStructure"];
            volatility: components["schemas"]["VolatilityProfile"];
            flow: components["schemas"]["FlowSnapshot"];
            vrp: components["schemas"]["VRPAssessment"];
            setup?: components["schemas"]["SetupClassification"] | null;
            trade_plan?: components["schemas"]["TradePlan"] | null;
            /** Dark Pool Notional */
            dark_pool_notional?: string | null;
            /**
             * Dark Pool Print Count
             * @default 0
             */
            dark_pool_print_count: number;
            short_data?: components["schemas"]["ShortDataRow"] | null;
            /**
             * Max Pain Rows
             * @default []
             */
            max_pain_rows: components["schemas"]["MaxPainRow"][];
            /**
             * Oi Change Top
             * @default []
             */
            oi_change_top: components["schemas"]["OiChangeRow"][];
            aggregates?: components["schemas"]["MarketAggregates"] | null;
            /**
             * Strike Gex Curve
             * @default []
             */
            strike_gex_curve: components["schemas"]["StrikeGexBucket"][];
            market_structure_levels?: components["schemas"]["MarketStructureLevels"] | null;
        };
        /** SkewBlock */
        SkewBlock: {
            /** Rr25D 30Dte */
            rr25d_30dte?: string | null;
        };
        /** SmileExpiryCurve */
        SmileExpiryCurve: {
            /**
             * Expiry
             * Format: date
             */
            expiry: string;
            /**
             * Points
             * @default []
             */
            points: components["schemas"]["SmilePoint"][];
        };
        /** SmilePoint */
        SmilePoint: {
            /** Strike */
            strike: string;
            /** Iv */
            iv?: string | null;
        };
        /** StockHistoryResponse */
        StockHistoryResponse: {
            /** Ticker */
            ticker: string;
            /**
             * Rows
             * @default []
             */
            rows: components["schemas"]["StockHistoryRow"][];
        };
        /**
         * StockHistoryRow
         * @description One per-trading-day rollup of a ticker's market structure.
         *
         *     Built from the latest successful scan_run on that date. spot comes from
         *     daily_ohlc.close so it's a stable end-of-day reference (NULL for the
         *     current trading day until the OHLC pull fires post-close).
         */
        StockHistoryRow: {
            /**
             * Market Date
             * Format: date
             */
            market_date: string;
            /** Spot */
            spot?: string | null;
            /** Gex Flip */
            gex_flip?: string | null;
            /** Net Gex */
            net_gex?: string | null;
            /** Net Dex */
            net_dex?: string | null;
            /** Iv30D */
            iv30d?: string | null;
            /** Pcr Vol */
            pcr_vol?: string | null;
            /**
             * Bias
             * @default NEUTRAL
             */
            bias: string;
        };
        /**
         * StrikeGexBucket
         * @description One row of the per-strike, per-expiry GEX curve persisted on each scan run.
         */
        StrikeGexBucket: {
            /** Strike */
            strike: string;
            /**
             * Expiry
             * Format: date
             */
            expiry: string;
            /** Net Gex */
            net_gex?: string | null;
            /** Call Gex */
            call_gex?: string | null;
            /** Put Gex */
            put_gex?: string | null;
        };
        /** TermStructureExpiryRow */
        TermStructureExpiryRow: {
            /**
             * Expiry
             * Format: date
             */
            expiry: string;
            /** Dte */
            dte?: number | null;
            /**
             * By Strike
             * @default {}
             */
            by_strike: {
                [key: string]: string;
            };
        };
        /** TradePlan */
        TradePlan: {
            /** Structure */
            structure: string;
            /** Direction */
            direction: string;
            /**
             * Legs
             * @default []
             */
            legs: components["schemas"]["TradePlanLeg"][];
            /** Rationale */
            rationale: string;
            /** Max Loss */
            max_loss?: string | null;
            /** Max Profit */
            max_profit?: string | null;
        };
        /** TradePlanLeg */
        TradePlanLeg: {
            /** Option Symbol */
            option_symbol: string;
            /** Side */
            side: string;
            /** Strike */
            strike: string;
            /**
             * Expiry
             * Format: date
             */
            expiry: string;
            /** Mid */
            mid?: string | null;
        };
        /** VRPAssessment */
        VRPAssessment: {
            /** Vrp */
            vrp?: string | null;
            /** Signal */
            signal: string;
            /** Note */
            note: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VolHeaderBlock */
        VolHeaderBlock: {
            /** Iv */
            iv?: string | null;
            /** Rv */
            rv?: string | null;
            /** Iv Rank */
            iv_rank?: string | null;
            /** Iv Rank 1Y */
            iv_rank_1y?: string | null;
            /** Iv Low 52W */
            iv_low_52w?: string | null;
            /** Iv High 52W */
            iv_high_52w?: string | null;
            /** Rv Low 52W */
            rv_low_52w?: string | null;
            /** Rv High 52W */
            rv_high_52w?: string | null;
            /** Iv Percentile 30D */
            iv_percentile_30d?: string | null;
            /** Implied Move 30D Perc */
            implied_move_30d_perc?: string | null;
            /** Skew 25D */
            skew_25d?: string | null;
            /** Vrp */
            vrp?: string | null;
            /**
             * Vrp Signal
             * @default
             */
            vrp_signal: string;
            /**
             * Vrp Note
             * @default
             */
            vrp_note: string;
        };
        /** VolatilityProfile */
        VolatilityProfile: {
            /** Iv */
            iv?: string | null;
            /** Iv Rank */
            iv_rank?: string | null;
            /** Iv Low 52W */
            iv_low_52w?: string | null;
            /** Iv High 52W */
            iv_high_52w?: string | null;
            /** Rv */
            rv?: string | null;
            /** Rv Low 52W */
            rv_low_52w?: string | null;
            /** Rv High 52W */
            rv_high_52w?: string | null;
            /** Iv Rank 1Y */
            iv_rank_1y?: string | null;
            /** Iv Percentile 30D */
            iv_percentile_30d?: string | null;
            /** Implied Move 30D Perc */
            implied_move_30d_perc?: string | null;
            /** Skew 25D */
            skew_25d?: string | null;
            /**
             * Term Dte To Iv
             * @default []
             */
            term_dte_to_iv: [
                number,
                string
            ][];
        };
        /** VolatilitySeriesResponse */
        VolatilitySeriesResponse: {
            /** Ticker */
            ticker: string;
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Backfill Status */
            backfill_status: string;
            header: components["schemas"]["VolHeaderBlock"];
            /**
             * Term Structure
             * @default []
             */
            term_structure: components["schemas"]["TermStructureExpiryRow"][];
            /**
             * Smile
             * @default []
             */
            smile: components["schemas"]["SmileExpiryCurve"][];
            /**
             * Hv Iv History
             * @default []
             */
            hv_iv_history: components["schemas"]["IvHvPoint"][];
            /**
             * @default {
             *       "bins": []
             *     }
             */
            iv_percentile_distribution: components["schemas"]["IvPercentileDistribution"];
            /**
             * Iv Of Iv
             * @default []
             */
            iv_of_iv: components["schemas"]["IvOfIvPoint"][];
            /**
             * Rv Spy Corr
             * @default []
             */
            rv_spy_corr: components["schemas"]["RvCorrPoint"][];
            /**
             * @default {
             *       "points": []
             *     }
             */
            regime_quadrant: components["schemas"]["RegimeQuadrantBlock"];
            /**
             * Divergence
             * @default []
             */
            divergence: components["schemas"]["DivergencePoint"][];
            /**
             * Divergence Headline
             * @default
             */
            divergence_headline: string;
            /**
             * Vrp Spread
             * @default []
             */
            vrp_spread: components["schemas"]["VrpDailyPoint"][];
            /**
             * Vrp Spread Headline
             * @default
             */
            vrp_spread_headline: string;
        };
        /** VrpDailyPoint */
        VrpDailyPoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Vrp */
            vrp?: string | null;
            /** Vrp Z 20 */
            vrp_z_20?: string | null;
        };
        /** WatchlistCard */
        WatchlistCard: {
            /** Ticker */
            ticker: string;
            /** Sector */
            sector: string;
            /** Pinned */
            pinned: boolean;
            /** Sort Rank */
            sort_rank: number;
            /** Spot */
            spot?: string | null;
            /** Spot Quoted At */
            spot_quoted_at?: string | null;
            /** Spot Source */
            spot_source?: string | null;
            /** Scanned At */
            scanned_at?: string | null;
            /** Iv Atm */
            iv_atm?: string | null;
            /** Iv Rank */
            iv_rank?: string | null;
            setup: components["schemas"]["SetupBlock"];
            /** Aggression Pct */
            aggression_pct?: string | null;
            returns: components["schemas"]["ReturnsBlock"];
            gamma: components["schemas"]["GammaBlock"];
            skew: components["schemas"]["SkewBlock"];
            positioning: components["schemas"]["PositioningBlock"];
        };
        /** WatchlistMutation */
        WatchlistMutation: {
            /** Ticker */
            ticker: string;
            /** Sector */
            sector: string;
            /** Notes */
            notes?: string | null;
            /**
             * Pinned
             * @default false
             */
            pinned: boolean;
            /**
             * Sort Rank
             * @default 0
             */
            sort_rank: number;
        };
        /** WatchlistPatch */
        WatchlistPatch: {
            /** Sector */
            sector?: string | null;
            /** Notes */
            notes?: string | null;
            /** Pinned */
            pinned?: boolean | null;
            /** Sort Rank */
            sort_rank?: number | null;
        };
        /** WatchlistResponse */
        WatchlistResponse: {
            /** Scanned At Min */
            scanned_at_min?: string | null;
            /** Scanned At Max */
            scanned_at_max?: string | null;
            /** Scheduler Lag Seconds */
            scheduler_lag_seconds?: number | null;
            /** Tickers */
            tickers: components["schemas"]["WatchlistCard"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_watchlist_api_watchlist_get: {
        parameters: {
            query?: {
                sector?: string | null;
                /** @description e.g. 'C-bull', 'C-bear', 'F-MULTI', 'NEUTRAL' */
                setup?: string | null;
                fresh_within_minutes?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_watchlist_api_watchlist_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistMutation"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_watchlist_api_watchlist__ticker__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_watchlist_api_watchlist__ticker__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stock_api_stock__ticker__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SingleStockReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stock_history_api_stock__ticker__history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_stock__ticker__runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_specific_run_api_stock__ticker__runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SingleStockReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ohlc_api_ohlc__ticker__get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OhlcRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enqueue_rescan_api_watchlist__ticker__rescan_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enqueue_rescan_all_api_watchlist_rescan_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"][];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_volatility_series_api_stock__ticker__volatility_series_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VolatilitySeriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
