/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ohlc/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ohlc */
        get: operations["get_ohlc_api_ohlc__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/provider-usage/endpoints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Provider Usage Endpoints */
        get: operations["provider_usage_endpoints_api_provider_usage_endpoints_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/provider-usage/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Provider Usage Requests */
        get: operations["provider_usage_requests_api_provider_usage_requests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/provider-usage/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Provider Usage Summary */
        get: operations["provider_usage_summary_api_provider_usage_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/provider-usage/tickers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Provider Usage Tickers */
        get: operations["provider_usage_tickers_api_provider_usage_tickers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stock/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stock */
        get: operations["get_stock_api_stock__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stock/{ticker}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stock History
         * @description Daily rollup for the Market Structure tab's history table.
         *
         *     One row per trading day, sorted newest-first. Today's row may have
         *     spot=None if the post-close OHLC pull hasn't fired yet.
         */
        get: operations["get_stock_history_api_stock__ticker__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stock/{ticker}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_stock__ticker__runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stock/{ticker}/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Specific Run */
        get: operations["get_specific_run_api_stock__ticker__runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stock/{ticker}/trade-insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trade Insights */
        get: operations["get_trade_insights_api_stock__ticker__trade_insights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stock/{ticker}/trade-insights/ai-analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Trade Insights Ai Analysis */
        post: operations["post_trade_insights_ai_analysis_api_stock__ticker__trade_insights_ai_analysis_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stock/{ticker}/trade-insights/ai-analysis/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Latest Trade Insights Ai Analysis */
        get: operations["get_latest_trade_insights_ai_analysis_api_stock__ticker__trade_insights_ai_analysis_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stock/{ticker}/trade-insights/ai-analysis/{analysis_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trade Insights Ai Analysis */
        get: operations["get_trade_insights_ai_analysis_api_stock__ticker__trade_insights_ai_analysis__analysis_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stock/{ticker}/volatility/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Volatility Series */
        get: operations["get_volatility_series_api_stock__ticker__volatility_series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Watchlist */
        get: operations["get_watchlist_api_watchlist_get"];
        put?: never;
        /** Post Watchlist */
        post: operations["post_watchlist_api_watchlist_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlist/rescan-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enqueue Rescan All
         * @description Enqueue a rescan job for every active watchlist ticker.
         */
        post: operations["enqueue_rescan_all_api_watchlist_rescan_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlist/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Watchlist */
        delete: operations["delete_watchlist_api_watchlist__ticker__delete"];
        options?: never;
        head?: never;
        /** Patch Watchlist */
        patch: operations["patch_watchlist_api_watchlist__ticker__patch"];
        trace?: never;
    };
    "/api/watchlist/{ticker}/rescan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enqueue Rescan */
        post: operations["enqueue_rescan_api_watchlist__ticker__rescan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CandidateStructure */
        CandidateStructure: {
            /**
             * Breakevens
             * @default []
             */
            breakevens: string[];
            /**
             * Edge Source
             * @default
             */
            edge_source: string;
            /** Expression Type */
            expression_type: string;
            /** Idea Id */
            idea_id: string;
            /**
             * Legs
             * @default []
             */
            legs: components["schemas"]["InsightLeg"][];
            /** Max Loss */
            max_loss?: string | null;
            /** Max Profit */
            max_profit?: string | null;
            /** Net Credit Debit */
            net_credit_debit?: string | null;
            /**
             * Profit Zone
             * @default
             */
            profit_zone: string;
            /** Rank */
            rank: number;
            /**
             * Risk Flags
             * @default []
             */
            risk_flags: string[];
            /**
             * Status
             * @default candidate
             */
            status: string;
            /** Structure */
            structure: string;
            /** Thesis */
            thesis: string;
        };
        /** ChainFlowReadRow */
        ChainFlowReadRow: {
            /** Call Open Interest */
            call_open_interest?: number | null;
            /** Call Put Volume Ratio */
            call_put_volume_ratio?: string | null;
            /** Call Volume */
            call_volume?: number | null;
            /** Put Open Interest */
            put_open_interest?: number | null;
            /** Put Volume */
            put_volume?: number | null;
            /**
             * Read
             * @default
             */
            read: string;
            /**
             * Requires T1 Oi Confirmation
             * @default false
             */
            requires_t1_oi_confirmation: boolean;
            /** Strike */
            strike: string;
            /**
             * Volume Oi Note
             * @default
             */
            volume_oi_note: string;
        };
        /** DivergencePoint */
        DivergencePoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Iv Z */
            iv_z?: string | null;
            /** Rv Z */
            rv_z?: string | null;
        };
        /** FlowAlert */
        FlowAlert: {
            /** Alert Rule */
            alert_rule?: string | null;
            /** All Opening Trades */
            all_opening_trades?: boolean | null;
            /** Created At */
            created_at?: string | null;
            /** Expiry */
            expiry?: string | null;
            /** Has Floor */
            has_floor?: boolean | null;
            /** Has Multileg */
            has_multileg?: boolean | null;
            /** Has Sweep */
            has_sweep?: boolean | null;
            /** Id */
            id: string;
            /** Issue Type */
            issue_type?: string | null;
            /** Iv End */
            iv_end?: string | null;
            /** Iv Start */
            iv_start?: string | null;
            /** Next Earnings Date */
            next_earnings_date?: string | null;
            /** Open Interest */
            open_interest?: number | null;
            /** Option Chain */
            option_chain?: string | null;
            /** Price */
            price?: string | null;
            /** Rule Id */
            rule_id?: string | null;
            /** Sector */
            sector?: string | null;
            /** Strike */
            strike?: string | null;
            /** Ticker */
            ticker: string;
            /** Total Ask Side Prem */
            total_ask_side_prem?: string | null;
            /** Total Bid Side Prem */
            total_bid_side_prem?: string | null;
            /** Total Premium */
            total_premium?: string | null;
            /** Total Size */
            total_size?: number | null;
            /** Type */
            type?: string | null;
            /** Underlying Price */
            underlying_price?: string | null;
            /** Volume */
            volume?: number | null;
            /** Volume Oi Ratio */
            volume_oi_ratio?: string | null;
        };
        /** FlowSnapshot */
        FlowSnapshot: {
            /** Ask Side Premium */
            ask_side_premium: string;
            /** Bear Premium */
            bear_premium: string;
            /** Bid Side Premium */
            bid_side_premium: string;
            /** Bull Premium */
            bull_premium: string;
            /** Flow Count */
            flow_count: number;
            /** Flow Count 30D Avg */
            flow_count_30d_avg?: string | null;
            /**
             * Flow Count 30D Days
             * @default 0
             */
            flow_count_30d_days: number;
            /**
             * Flow Count Is Limited
             * @default false
             */
            flow_count_is_limited: boolean;
            /** Flow Count Vs 30D Avg */
            flow_count_vs_30d_avg?: string | null;
            /** Net Premium */
            net_premium: string;
            /** Ticker */
            ticker: string;
            /** Top Alert Rule */
            top_alert_rule?: string | null;
            /**
             * Top Alerts
             * @default []
             */
            top_alerts: components["schemas"]["FlowAlert"][];
        };
        /** GammaBlock */
        GammaBlock: {
            /** Expiring Date */
            expiring_date?: string | null;
            /** Expiring Pct */
            expiring_pct?: string | null;
            /** Flip Distance */
            flip_distance?: string | null;
            /** Flip Price */
            flip_price?: string | null;
            /** Max Strike */
            max_strike?: string | null;
            /** Per 1Pct Move */
            per_1pct_move?: string | null;
        };
        /**
         * GexLevel
         * @description One labeled level on the GEX curve (e.g. CALL WALL, PUT WALL, MAX MAGNET).
         *
         *     `gamma_per_dollar` is the per-strike net_gex used as the "$N per $1" sensitivity
         *     figure on the tile — the dollar value of dealer hedging triggered by a $1 move.
         */
        GexLevel: {
            /** Gamma Per Dollar */
            gamma_per_dollar?: string | null;
            /** Net Gex */
            net_gex?: string | null;
            /** Pct From Spot */
            pct_from_spot?: string | null;
            /** Strike */
            strike: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Cache Hit Pct */
            cache_hit_pct?: number | null;
            /** Db */
            db: string;
            /** Http 2Xx */
            http_2xx?: number | null;
            /** Http 4Xx */
            http_4xx?: number | null;
            /** Http 5Xx */
            http_5xx?: number | null;
            /** Last Full Scan At */
            last_full_scan_at?: string | null;
            /** Latency P95 Ms */
            latency_p95_ms?: number | null;
            /** Latest Spot Quote At */
            latest_spot_quote_at?: string | null;
            /** Latest Spot Quote Fetched At */
            latest_spot_quote_fetched_at?: string | null;
            /** Ok */
            ok: boolean;
            /** Reason */
            reason?: string | null;
            /** Record Health */
            record_health?: components["schemas"]["RecordHealthCheck"][];
            /** Record Health Ok */
            record_health_ok?: boolean | null;
            /** Rescan Heartbeat Lag Seconds */
            rescan_heartbeat_lag_seconds?: number | null;
            /** Scheduler Heartbeat Lag Seconds */
            scheduler_heartbeat_lag_seconds?: number | null;
            /** Scheduler Heartbeat Name */
            scheduler_heartbeat_name?: string | null;
            /** Scheduler Lag Seconds */
            scheduler_lag_seconds?: number | null;
            /**
             * Source
             * @default UnusualWhales
             */
            source: string;
            /** Spot Quote Lag Seconds */
            spot_quote_lag_seconds?: number | null;
            /** Spot Refresh Heartbeat Lag Seconds */
            spot_refresh_heartbeat_lag_seconds?: number | null;
            /** Uw Today */
            uw_today?: number | null;
            /** Watchlist Size */
            watchlist_size?: number | null;
            /** Worker Lag Seconds */
            worker_lag_seconds?: number | null;
            /** Workers */
            workers?: components["schemas"]["WorkerHealth"][];
        };
        /** InsightBadge */
        InsightBadge: {
            /** Code */
            code: string;
            /** Label */
            label: string;
            /**
             * Severity
             * @default info
             */
            severity: string;
        };
        /** InsightLeg */
        InsightLeg: {
            /**
             * Expiry
             * Format: date
             */
            expiry: string;
            /** Mid */
            mid?: string | null;
            /** Option Right */
            option_right: string;
            /** Option Symbol */
            option_symbol: string;
            /** Side */
            side: string;
            /** Strike */
            strike: string;
        };
        /** InsightSignalRow */
        InsightSignalRow: {
            /**
             * Conflicts
             * @default []
             */
            conflicts: string[];
            /**
             * Evidence
             * @default []
             */
            evidence: string[];
            /** Lens */
            lens: string;
            /** Read */
            read: string;
        };
        /** InsightsSynthesis */
        InsightsSynthesis: {
            /**
             * Avoid
             * @default []
             */
            avoid: string[];
            /** Best Risk Reward Idea Id */
            best_risk_reward_idea_id?: string | null;
            /**
             * Dominant Story
             * @default
             */
            dominant_story: string;
            /** Preferred Idea Id */
            preferred_idea_id?: string | null;
            /**
             * Required Before Sizing
             * @default []
             */
            required_before_sizing: string[];
        };
        /** IvHistogramBin */
        IvHistogramBin: {
            /** Count */
            count: number;
            /** Hi */
            hi: string;
            /** Lo */
            lo: string;
        };
        /** IvHvPoint */
        IvHvPoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Iv */
            iv?: string | null;
            /** Rv */
            rv?: string | null;
        };
        /** IvOfIvPoint */
        IvOfIvPoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Iv */
            iv?: string | null;
            /** Iv Of Iv 20 */
            iv_of_iv_20?: string | null;
        };
        /** IvPercentileDistribution */
        IvPercentileDistribution: {
            /**
             * Bins
             * @default []
             */
            bins: components["schemas"]["IvHistogramBin"][];
            /** Current Iv */
            current_iv?: string | null;
            /** Current Pctile */
            current_pctile?: string | null;
        };
        /** JobStatus */
        JobStatus: {
            /** Error */
            error?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Job Id */
            job_id: string;
            /**
             * Requested At
             * Format: date-time
             */
            requested_at: string;
            /** Run Id */
            run_id?: number | null;
            /** Started At */
            started_at?: string | null;
            /** Status */
            status: string;
        };
        /**
         * MarketAggregates
         * @description Per-ticker aggregate fields sourced from the bulk-screener endpoint.
         *
         *     Populated by pipeline.run_single_stock alongside the existing per-section
         *     sub-models. Feeds the watchlist card POSITIONING and SKEW blocks.
         */
        MarketAggregates: {
            /** Call Oi Total */
            call_oi_total?: number | null;
            /** Call Volume Ask Side */
            call_volume_ask_side?: number | null;
            /** Call Volume Bid Side */
            call_volume_bid_side?: number | null;
            /** Call Volume Total */
            call_volume_total?: number | null;
            /** Iv30D */
            iv30d?: string | null;
            /** Pcr Oi */
            pcr_oi?: string | null;
            /** Pcr Vol */
            pcr_vol?: string | null;
            /** Put Oi Total */
            put_oi_total?: number | null;
            /** Put Volume Ask Side */
            put_volume_ask_side?: number | null;
            /** Put Volume Bid Side */
            put_volume_bid_side?: number | null;
            /** Put Volume Total */
            put_volume_total?: number | null;
        };
        /** MarketStructure */
        MarketStructure: {
            /** Max Pain */
            max_pain?: string | null;
            /** Nearest Expiry */
            nearest_expiry?: string | null;
            /** Net Gex */
            net_gex?: string | null;
            /** Spot */
            spot?: string | null;
            /**
             * Top Call Oi Strikes
             * @default []
             */
            top_call_oi_strikes: string[];
            /**
             * Top Put Oi Strikes
             * @default []
             */
            top_put_oi_strikes: string[];
            /** Total Call Dex Oi */
            total_call_dex_oi?: string | null;
            /** Total Call Gex */
            total_call_gex?: string | null;
            /** Total Put Dex Oi */
            total_put_dex_oi?: string | null;
            /** Total Put Gex */
            total_put_gex?: string | null;
        };
        /**
         * MarketStructureLevels
         * @description Derived strike-level reference points used by the Market Structure tab.
         *
         *     Conventions follow FlashAlpha / SpotGamma:
         *       - gex_flip: lowest strike where running cumulative net_gex flips sign
         *       - call_wall: strike with largest call-side gamma (typically above spot)
         *       - put_wall: strike with largest put-side gamma magnitude (typically below spot)
         *       - max_magnet: strike with largest positive net_gex above spot (pulls price up)
         *       - second_magnet: strike with second-largest positive net_gex above spot
         *       - max_accel: strike with most-negative net_gex below the flip (movement accelerator)
         */
        MarketStructureLevels: {
            call_wall?: components["schemas"]["GexLevel"] | null;
            gex_flip?: components["schemas"]["GexLevel"] | null;
            max_accel?: components["schemas"]["GexLevel"] | null;
            max_magnet?: components["schemas"]["GexLevel"] | null;
            put_wall?: components["schemas"]["GexLevel"] | null;
            second_magnet?: components["schemas"]["GexLevel"] | null;
        };
        /** MaxPainRow */
        MaxPainRow: {
            /** Close */
            close?: string | null;
            /**
             * Expiry
             * Format: date
             */
            expiry: string;
            /** Max Pain */
            max_pain?: string | null;
            /** Next Lower Strike */
            next_lower_strike?: string | null;
            /** Next Upper Strike */
            next_upper_strike?: string | null;
            /** Open */
            open?: string | null;
        };
        /** OhlcRow */
        OhlcRow: {
            /** Close */
            close: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** High */
            high?: string | null;
            /** Low */
            low?: string | null;
            /** Open */
            open?: string | null;
            /** Volume */
            volume?: number | null;
        };
        /** OiChangeRow */
        OiChangeRow: {
            /** Ask Volume */
            ask_volume?: number | null;
            /** Avg Price */
            avg_price?: string | null;
            /** Bid Volume */
            bid_volume?: number | null;
            /** Curr Date */
            curr_date?: string | null;
            /** Curr Oi */
            curr_oi?: number | null;
            /** Days Of Oi Increases */
            days_of_oi_increases?: number | null;
            /** Days Of Vol Greater Than Oi */
            days_of_vol_greater_than_oi?: number | null;
            /** Last Ask */
            last_ask?: string | null;
            /** Last Bid */
            last_bid?: string | null;
            /** Last Date */
            last_date?: string | null;
            /** Last Fill */
            last_fill?: string | null;
            /** Last Oi */
            last_oi?: number | null;
            /** Mid Volume */
            mid_volume?: number | null;
            /** No Side Volume */
            no_side_volume?: number | null;
            /** Oi Change */
            oi_change?: string | null;
            /** Oi Diff Plain */
            oi_diff_plain?: number | null;
            /** Option Symbol */
            option_symbol: string;
            /** Percentage Of Total */
            percentage_of_total?: string | null;
            /** Prev Ask Volume */
            prev_ask_volume?: number | null;
            /** Prev Bid Volume */
            prev_bid_volume?: number | null;
            /** Prev Mid Volume */
            prev_mid_volume?: number | null;
            /** Prev Multi Leg Volume */
            prev_multi_leg_volume?: number | null;
            /** Prev Neutral Volume */
            prev_neutral_volume?: number | null;
            /** Prev Stock Multi Leg Volume */
            prev_stock_multi_leg_volume?: number | null;
            /** Prev Total Premium */
            prev_total_premium?: string | null;
            /** Rnk */
            rnk?: number | null;
            /** Trades */
            trades?: number | null;
            /** Underlying Symbol */
            underlying_symbol: string;
            /** Volume */
            volume?: number | null;
        };
        /**
         * OptionChainPerStrikeRow
         * @description Aggregated (expiry, strike) snapshot — both volume and OI in one row.
         *
         *     Backs both strike-profile charts (Volume and OI variants).
         */
        OptionChainPerStrikeRow: {
            /** Call Oi */
            call_oi?: number | null;
            /** Call Volume */
            call_volume?: number | null;
            /**
             * Expiry
             * Format: date
             */
            expiry: string;
            /** Put Oi */
            put_oi?: number | null;
            /** Put Volume */
            put_volume?: number | null;
            /** Strike */
            strike: string;
        };
        /**
         * OptionsDailyRow
         * @description One row per trading day from UW /options-volume.
         *
         *     ``bullish_premium`` here is whole-tape (UW), distinct from the
         *     alert-scoped :class:`FlowSnapshot.bull_premium`. Do not cross-plot.
         */
        OptionsDailyRow: {
            /** Avg 30 Day Call Volume */
            avg_30_day_call_volume?: string | null;
            /** Avg 30 Day Put Volume */
            avg_30_day_put_volume?: string | null;
            /** Avg 3 Day Call Volume */
            avg_3_day_call_volume?: string | null;
            /** Avg 3 Day Put Volume */
            avg_3_day_put_volume?: string | null;
            /** Avg 7 Day Call Volume */
            avg_7_day_call_volume?: string | null;
            /** Avg 7 Day Put Volume */
            avg_7_day_put_volume?: string | null;
            /** Bearish Premium */
            bearish_premium?: string | null;
            /** Bullish Premium */
            bullish_premium?: string | null;
            /** Call Open Interest */
            call_open_interest?: number | null;
            /** Call Premium */
            call_premium?: string | null;
            /** Call Volume */
            call_volume?: number | null;
            /** Call Volume Ask Side */
            call_volume_ask_side?: number | null;
            /** Call Volume Bid Side */
            call_volume_bid_side?: number | null;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Net Call Premium */
            net_call_premium?: string | null;
            /** Net Put Premium */
            net_put_premium?: string | null;
            /** Put Open Interest */
            put_open_interest?: number | null;
            /** Put Premium */
            put_premium?: string | null;
            /** Put Volume */
            put_volume?: number | null;
            /** Put Volume Ask Side */
            put_volume_ask_side?: number | null;
            /** Put Volume Bid Side */
            put_volume_bid_side?: number | null;
        };
        /** PositioningBlock */
        PositioningBlock: {
            /** Call Oi */
            call_oi?: number | null;
            /** Pcr Delta 30D */
            pcr_delta_30d?: string | null;
            /** Pcr Oi */
            pcr_oi?: string | null;
            /** Pcr Vol */
            pcr_vol?: string | null;
            /** Put Oi */
            put_oi?: number | null;
        };
        /** ProviderUsageBreakdownResponse */
        ProviderUsageBreakdownResponse: {
            /**
             * Provider Day End
             * Format: date-time
             */
            provider_day_end: string;
            /**
             * Provider Day Start
             * Format: date-time
             */
            provider_day_start: string;
            /** Rows */
            rows: components["schemas"]["ProviderUsageBreakdownRow"][];
        };
        /** ProviderUsageBreakdownRow */
        ProviderUsageBreakdownRow: {
            /** Http 2Xx */
            http_2xx: number;
            /** Http 3Xx */
            http_3xx: number;
            /** Http 4Xx */
            http_4xx: number;
            /** Http 5Xx */
            http_5xx: number;
            /** Key */
            key: string | null;
            /** Latency P95 Ms */
            latency_p95_ms: number | null;
            /** Total Requests */
            total_requests: number;
            /** Transport Errors */
            transport_errors: number;
        };
        /** ProviderUsageRequestRow */
        ProviderUsageRequestRow: {
            /** Attempt */
            attempt: number;
            /** Endpoint Key */
            endpoint_key: string;
            /** Error Message */
            error_message: string | null;
            /** Job Name */
            job_name: string | null;
            /** Latency Ms */
            latency_ms: number;
            /** Method */
            method: string;
            /** Official Daily Count */
            official_daily_count: number | null;
            /** Official Daily Limit */
            official_daily_limit: number | null;
            /** Official Minute Remaining */
            official_minute_remaining: number | null;
            /** Official Minute Reset */
            official_minute_reset: string | null;
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /** Path */
            path: string;
            /** Provider */
            provider: string;
            /** Provider Request Id */
            provider_request_id: string | null;
            /**
             * Request Finished At
             * Format: date-time
             */
            request_finished_at: string;
            /** Request Id */
            request_id: number;
            /**
             * Request Started At
             * Format: date-time
             */
            request_started_at: string;
            /** Run Id */
            run_id: number | null;
            /** Status Code */
            status_code: number | null;
            /** Status Family */
            status_family: string;
            /** Ticker */
            ticker: string | null;
        };
        /** ProviderUsageRequestsResponse */
        ProviderUsageRequestsResponse: {
            /** Limit */
            limit: number;
            /**
             * Provider Day End
             * Format: date-time
             */
            provider_day_end: string;
            /**
             * Provider Day Start
             * Format: date-time
             */
            provider_day_start: string;
            /** Rows */
            rows: components["schemas"]["ProviderUsageRequestRow"][];
        };
        /** ProviderUsageSummaryResponse */
        ProviderUsageSummaryResponse: {
            /** Http 2Xx */
            http_2xx: number;
            /** Http 3Xx */
            http_3xx: number;
            /** Http 4Xx */
            http_4xx: number;
            /** Http 5Xx */
            http_5xx: number;
            /** Latency P95 Ms */
            latency_p95_ms: number | null;
            /**
             * Provider Day End
             * Format: date-time
             */
            provider_day_end: string;
            /**
             * Provider Day Start
             * Format: date-time
             */
            provider_day_start: string;
            /** Total Requests */
            total_requests: number;
            /** Transport Errors */
            transport_errors: number;
            /** Uw Latest Daily Count */
            uw_latest_daily_count: number | null;
            /** Uw Latest Daily Limit */
            uw_latest_daily_limit: number | null;
        };
        /** QueueStatus */
        QueueStatus: {
            /** Job Id */
            job_id: string;
            /** Queue Position */
            queue_position: number;
            /**
             * Requested At
             * Format: date-time
             */
            requested_at: string;
            /** Started At */
            started_at?: string | null;
            /** Status */
            status: string;
        };
        /** QueueSummary */
        QueueSummary: {
            /** Oldest Requested At */
            oldest_requested_at?: string | null;
            /**
             * Queued
             * @default 0
             */
            queued: number;
            /**
             * Running
             * @default 0
             */
            running: number;
            /**
             * Total
             * @default 0
             */
            total: number;
        };
        /** RecordHealthCheck */
        RecordHealthCheck: {
            /** Actual Rows */
            actual_rows: number;
            /** Actual Tickers */
            actual_tickers: number;
            /** Expected Min Rows */
            expected_min_rows: number;
            /** Expected Min Tickers */
            expected_min_tickers: number;
            /** Expected Tickers */
            expected_tickers: number;
            /** Latest At */
            latest_at?: string | null;
            /** Ok */
            ok: boolean;
            /** Table */
            table: string;
            /**
             * Window Start
             * Format: date-time
             */
            window_start: string;
        };
        /** RegimeQuadrantBlock */
        RegimeQuadrantBlock: {
            /** Cutoff Corr */
            cutoff_corr?: string | null;
            latest?: components["schemas"]["RegimeQuadrantLatest"] | null;
            /**
             * Points
             * @default []
             */
            points: components["schemas"]["RegimeQuadrantPoint"][];
        };
        /** RegimeQuadrantLatest */
        RegimeQuadrantLatest: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Rvol Pctile */
            rvol_pctile?: string | null;
            /** Spy Corr 21 */
            spy_corr_21?: string | null;
            /**
             * State
             * @default
             */
            state: string;
        };
        /** RegimeQuadrantPoint */
        RegimeQuadrantPoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Rvol Pctile */
            rvol_pctile?: string | null;
            /** Spy Corr 21 */
            spy_corr_21?: string | null;
        };
        /** RescanAllRequest */
        RescanAllRequest: {
            /**
             * Confirmed
             * @default false
             */
            confirmed: boolean;
        };
        /**
         * ReturnsBlock
         * @description Wire shape: d1 / w1 / d30. No aliases — FastAPI would otherwise serialize
         *     them as JSON keys and break the frontend contract.
         */
        ReturnsBlock: {
            /** D1 */
            d1?: string | null;
            /** D30 */
            d30?: string | null;
            /** W1 */
            w1?: string | null;
        };
        /** RvCorrPoint */
        RvCorrPoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Rv */
            rv?: string | null;
            /** Spy Corr 21 */
            spy_corr_21?: string | null;
        };
        /** SetupBlock */
        SetupBlock: {
            /** Direction */
            direction?: string | null;
            /** Score */
            score?: string | null;
            /** Type */
            type?: string | null;
        };
        /** SetupClassification */
        SetupClassification: {
            /**
             * Confirmations
             * @default []
             */
            confirmations: string[];
            /** Direction */
            direction: string;
            /** Label */
            label: string;
            /**
             * Notes
             * @default
             */
            notes: string;
            /** Score */
            score: string;
            /** Setup Type */
            setup_type: string;
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
        };
        /** ShortDataRow */
        ShortDataRow: {
            /** Fee Rate */
            fee_rate?: string | null;
            /** Name */
            name?: string | null;
            /** Rebate Rate */
            rebate_rate?: string | null;
            /** Short Shares Available */
            short_shares_available?: number | null;
            /** Symbol */
            symbol: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** SingleStockReport */
        SingleStockReport: {
            aggregates?: components["schemas"]["MarketAggregates"] | null;
            /** Dark Pool Notional */
            dark_pool_notional?: string | null;
            /**
             * Dark Pool Print Count
             * @default 0
             */
            dark_pool_print_count: number;
            flow: components["schemas"]["FlowSnapshot"];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            market_structure: components["schemas"]["MarketStructure"];
            market_structure_levels?: components["schemas"]["MarketStructureLevels"] | null;
            /**
             * Max Pain Rows
             * @default []
             */
            max_pain_rows: components["schemas"]["MaxPainRow"][];
            /** Next Earnings Date */
            next_earnings_date?: string | null;
            /**
             * Oi Change Top
             * @default []
             */
            oi_change_top: components["schemas"]["OiChangeRow"][];
            /**
             * Option Chain Per Strike
             * @default []
             */
            option_chain_per_strike: components["schemas"]["OptionChainPerStrikeRow"][];
            /**
             * Options Timeline
             * @default []
             */
            options_timeline: components["schemas"]["OptionsDailyRow"][];
            /** Run Id */
            run_id: number;
            setup?: components["schemas"]["SetupClassification"] | null;
            short_data?: components["schemas"]["ShortDataRow"] | null;
            /**
             * Short Int Note
             * @default n/a (UW endpoint does not expose %)
             */
            short_int_note: string;
            /** Spot Quoted At */
            spot_quoted_at?: string | null;
            /** Spot Source */
            spot_source?: string | null;
            /**
             * Strike Gex Curve
             * @default []
             */
            strike_gex_curve: components["schemas"]["StrikeGexBucket"][];
            /** Ticker */
            ticker: string;
            trade_plan?: components["schemas"]["TradePlan"] | null;
            volatility: components["schemas"]["VolatilityProfile"];
            vrp: components["schemas"]["VRPAssessment"];
        };
        /** SkewBlock */
        SkewBlock: {
            /** Rr25D 30Dte */
            rr25d_30dte?: string | null;
        };
        /** SmileExpiryCurve */
        SmileExpiryCurve: {
            /**
             * Expiry
             * Format: date
             */
            expiry: string;
            /**
             * Points
             * @default []
             */
            points: components["schemas"]["SmilePoint"][];
        };
        /** SmilePoint */
        SmilePoint: {
            /** Iv */
            iv?: string | null;
            /** Strike */
            strike: string;
        };
        /** SourceReconciliation */
        SourceReconciliation: {
            /**
             * Decision
             * @default Use deterministic data only where source agreement is understood.
             */
            decision: string;
            /**
             * Headline
             * @default Source reconciliation unavailable
             */
            headline: string;
            /** Primary Iv Source */
            primary_iv_source?: string | null;
            /** Relative Shape Source */
            relative_shape_source?: string | null;
            /**
             * Rows
             * @default []
             */
            rows: components["schemas"]["SourceReconciliationRow"][];
            /**
             * Status
             * @default UNKNOWN
             */
            status: string;
        };
        /** SourceReconciliationRow */
        SourceReconciliationRow: {
            /**
             * Decision
             * @default
             */
            decision: string;
            /**
             * Iv Agreement
             * @default
             */
            iv_agreement: string;
            /** Iv Diff */
            iv_diff?: string | null;
            /**
             * Price Agreement
             * @default
             */
            price_agreement: string;
            /** Source A Call Iv */
            source_a_call_iv?: string | null;
            /** Source B Call Iv */
            source_b_call_iv?: string | null;
            /** Source Pair */
            source_pair: string;
            /** Strike */
            strike?: string | null;
        };
        /** StockHistoryResponse */
        StockHistoryResponse: {
            /**
             * Rows
             * @default []
             */
            rows: components["schemas"]["StockHistoryRow"][];
            /** Ticker */
            ticker: string;
        };
        /**
         * StockHistoryRow
         * @description One per-trading-day rollup of a ticker's market structure.
         *
         *     Built from the latest successful scan_run on that date. spot comes from
         *     daily_ohlc.close so it's a stable end-of-day reference (NULL for the
         *     current trading day until the OHLC pull fires post-close).
         */
        StockHistoryRow: {
            /**
             * Bias
             * @default NEUTRAL
             */
            bias: string;
            /** Gex Flip */
            gex_flip?: string | null;
            /** Iv30D */
            iv30d?: string | null;
            /**
             * Market Date
             * Format: date
             */
            market_date: string;
            /** Net Dex */
            net_dex?: string | null;
            /** Net Gex */
            net_gex?: string | null;
            /** Pcr Vol */
            pcr_vol?: string | null;
            /** Spot */
            spot?: string | null;
        };
        /**
         * StrikeGexBucket
         * @description One row of the per-strike, per-expiry GEX curve persisted on each scan run.
         */
        StrikeGexBucket: {
            /** Call Gex */
            call_gex?: string | null;
            /**
             * Expiry
             * Format: date
             */
            expiry: string;
            /** Net Gex */
            net_gex?: string | null;
            /** Put Gex */
            put_gex?: string | null;
            /** Strike */
            strike: string;
        };
        /** TermMoveRow */
        TermMoveRow: {
            /** Atm Straddle */
            atm_straddle?: string | null;
            /** Daily Implied Move Perc */
            daily_implied_move_perc?: string | null;
            /** Dte */
            dte?: number | null;
            /**
             * Expiry
             * Format: date
             */
            expiry: string;
            /** Implied Move Perc */
            implied_move_perc?: string | null;
            /**
             * Read
             * @default
             */
            read: string;
        };
        /** TermStructureExpiryRow */
        TermStructureExpiryRow: {
            /**
             * By Strike
             * @default {}
             */
            by_strike: {
                [key: string]: string;
            };
            /** Dte */
            dte?: number | null;
            /**
             * Expiry
             * Format: date
             */
            expiry: string;
            /**
             * Strikes
             * @default {}
             */
            strikes: {
                [key: string]: string;
            };
        };
        /** TradeInsightAiAnalysisRequest */
        TradeInsightAiAnalysisRequest: {
            /**
             * Force Rerun
             * @default false
             */
            force_rerun: boolean;
        };
        /** TradeInsightAiAnalysisResponse */
        TradeInsightAiAnalysisResponse: {
            /**
             * Analysis Id
             * Format: uuid
             */
            analysis_id: string;
            /** Analysis Input Hash */
            analysis_input_hash: string;
            /** Error Message */
            error_message?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Markdown */
            markdown?: string | null;
            /** Model */
            model: string;
            outcome?: components["schemas"]["TradeInsightAiOutcome"] | null;
            /** Produced At */
            produced_at?: string | null;
            /** Prompt Version */
            prompt_version: string;
            /**
             * Requested At
             * Format: date-time
             */
            requested_at: string;
            /**
             * Reused
             * @default false
             */
            reused: boolean;
            /** Run Id */
            run_id: number;
            /** Started At */
            started_at?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed";
            /** Ticker */
            ticker: string;
            /** Trade Insights Input Hash */
            trade_insights_input_hash: string;
        };
        /** TradeInsightAiBestExpression */
        TradeInsightAiBestExpression: {
            /** Caveats */
            caveats?: string[];
            /** Idea Id */
            idea_id: string;
            /** Risk Flags Observed */
            risk_flags_observed?: string[];
            /** Role */
            role: string;
            /** Status Observed */
            status_observed: string;
            /** Structure */
            structure: string;
            /** Why */
            why: string;
        };
        /** TradeInsightAiConflict */
        TradeInsightAiConflict: {
            /** Affected Idea Ids */
            affected_idea_ids?: string[];
            /** Description */
            description: string;
            /** Lens */
            lens: string;
            /** Severity */
            severity: string;
        };
        /** TradeInsightAiDominantRead */
        TradeInsightAiDominantRead: {
            /** Confidence Commentary */
            confidence_commentary: string;
            /** Data Quality Commentary */
            data_quality_commentary: string;
            /** Headline */
            headline: string;
            /** Summary */
            summary: string;
        };
        /** TradeInsightAiGuardrails */
        TradeInsightAiGuardrails: {
            /** No Executable Recommendations */
            no_executable_recommendations: boolean;
            /** Risk Flags Preserved */
            risk_flags_preserved: boolean;
            /** Statuses Preserved */
            statuses_preserved: boolean;
        };
        /** TradeInsightAiHeadline */
        TradeInsightAiHeadline: {
            /** Conviction */
            conviction: string;
            /** Conviction Label */
            conviction_label: string;
            /** Primary Risk */
            primary_risk: string;
            /** Score */
            score: number;
            /**
             * Score Scale
             * @default 100
             */
            score_scale: number;
            /**
             * Stance
             * @enum {string}
             */
            stance: "bullish" | "bearish" | "neutral" | "mixed" | "wait";
            /** Stance Label */
            stance_label: string;
            /** Title */
            title: string;
            /** Top Reason */
            top_reason: string;
            /** Watch Trigger */
            watch_trigger: string;
        };
        /** TradeInsightAiHighlight */
        TradeInsightAiHighlight: {
            /** Label */
            label: string;
            /**
             * Note
             * @default
             */
            note: string;
            /** Source Path */
            source_path?: string | null;
            /** Value */
            value: string;
        };
        /** TradeInsightAiLevel */
        TradeInsightAiLevel: {
            /**
             * Importance
             * @default normal
             */
            importance: string;
            /** Kind */
            kind: string;
            /**
             * Note
             * @default
             */
            note: string;
            /** Price */
            price: string;
            /** Source Path */
            source_path?: string | null;
            /** Value */
            value: string;
        };
        /** TradeInsightAiMetricCard */
        TradeInsightAiMetricCard: {
            /** Label */
            label: string;
            /**
             * Note
             * @default
             */
            note: string;
            /** Source Path */
            source_path?: string | null;
            /**
             * Tone
             * @default neutral
             */
            tone: string;
            /** Value */
            value: string;
        };
        /** TradeInsightAiOutcome */
        TradeInsightAiOutcome: {
            /**
             * Analysis Produced At
             * Format: date-time
             */
            analysis_produced_at: string;
            /** Best Expressions */
            best_expressions?: components["schemas"]["TradeInsightAiBestExpression"][];
            /** Conflicts */
            conflicts?: components["schemas"]["TradeInsightAiConflict"][];
            dominant_read: components["schemas"]["TradeInsightAiDominantRead"];
            guardrails: components["schemas"]["TradeInsightAiGuardrails"];
            headline: components["schemas"]["TradeInsightAiHeadline"];
            /** Metric Cards */
            metric_cards: components["schemas"]["TradeInsightAiMetricCard"][];
            /** Missing Data */
            missing_data?: string[];
            preferred_expression?: components["schemas"]["TradeInsightAiPreferredExpression"] | null;
            /** Rejected Ideas */
            rejected_ideas?: components["schemas"]["TradeInsightAiRejectedIdea"][];
            rendering: components["schemas"]["TradeInsightAiRendering"];
            /** Required Checks */
            required_checks?: components["schemas"]["TradeInsightAiRequiredCheck"][];
            /** Scenario Cards */
            scenario_cards: components["schemas"]["TradeInsightAiScenarioCard"][];
            /** Schema Version */
            schema_version: string;
            /** Score Breakdown */
            score_breakdown: components["schemas"]["TradeInsightAiScoreBreakdown"][];
            section_cards: components["schemas"]["TradeInsightAiSectionCards"];
            snapshot: components["schemas"]["TradeInsightAiSnapshotMeta"];
            /** Ticker */
            ticker: string;
            /** Underlying Price */
            underlying_price?: string | null;
            vrp_assessment?: components["schemas"]["TradeInsightAiVrpAssessment"] | null;
        };
        /** TradeInsightAiPreferredExpression */
        TradeInsightAiPreferredExpression: {
            /**
             * Estimated Entry
             * @default
             */
            estimated_entry: string;
            /** Idea Id */
            idea_id: string;
            /** Management Notes */
            management_notes?: string[];
            /**
             * Max Loss Observed
             * @default
             */
            max_loss_observed: string;
            /**
             * Max Profit Observed
             * @default
             */
            max_profit_observed: string;
            /**
             * Reward Risk
             * @default
             */
            reward_risk: string;
            /** Risk Flags Observed */
            risk_flags_observed?: string[];
            /** Status Observed */
            status_observed: string;
            /** Structure */
            structure: string;
            /**
             * Subtitle
             * @default
             */
            subtitle: string;
            /** Title */
            title: string;
            /** Why */
            why: string;
        };
        /** TradeInsightAiRejectedIdea */
        TradeInsightAiRejectedIdea: {
            /** Idea Id */
            idea_id: string;
            /** Reason */
            reason: string;
            /** Structure */
            structure: string;
        };
        /** TradeInsightAiRendering */
        TradeInsightAiRendering: {
            /** Card Order */
            card_order?: string[];
            /** Disclaimer */
            disclaimer: string;
        };
        /** TradeInsightAiRequiredCheck */
        TradeInsightAiRequiredCheck: {
            /**
             * Blocks Sizing
             * @default true
             */
            blocks_sizing: boolean;
            /** Check */
            check: string;
            /** Reason */
            reason: string;
            /**
             * Source
             * @default
             */
            source: string;
        };
        /** TradeInsightAiScenarioCard */
        TradeInsightAiScenarioCard: {
            /** Case */
            case: ("upside" | "base" | "downside") | string;
            /** Description */
            description: string;
            /** Title */
            title: string;
            /**
             * Tone
             * @default neutral
             */
            tone: string;
        };
        /** TradeInsightAiScoreBreakdown */
        TradeInsightAiScoreBreakdown: {
            /** Max Score */
            max_score: number;
            /** Score */
            score: number;
            /** Section */
            section: string;
            /** Summary */
            summary: string;
        };
        /** TradeInsightAiSectionCard */
        TradeInsightAiSectionCard: {
            /**
             * Data Quality
             * @default unknown
             */
            data_quality: string;
            /** Highlights */
            highlights?: components["schemas"]["TradeInsightAiHighlight"][];
            /** Levels */
            levels?: components["schemas"]["TradeInsightAiLevel"][];
            /** Max Score */
            max_score?: number | null;
            /** Score */
            score?: number | null;
            /** Summary */
            summary: string;
            /** Title */
            title: string;
        };
        /** TradeInsightAiSectionCards */
        TradeInsightAiSectionCards: {
            flow_positioning: components["schemas"]["TradeInsightAiSectionCard"];
            market_structure: components["schemas"]["TradeInsightAiSectionCard"];
            volatility: components["schemas"]["TradeInsightAiSectionCard"];
        };
        /** TradeInsightAiSnapshotMeta */
        TradeInsightAiSnapshotMeta: {
            /** Analysis Input Hash */
            analysis_input_hash: string;
            /** Data As Of */
            data_as_of?: string | null;
            /**
             * Freshness Label
             * @default unknown
             */
            freshness_label: string;
            /** Run Id */
            run_id: number;
            /** Source Notes */
            source_notes?: string[];
            /** Trade Insights Input Hash */
            trade_insights_input_hash: string;
        };
        /** TradeInsightAiVrpAssessment */
        TradeInsightAiVrpAssessment: {
            /** Metrics */
            metrics?: components["schemas"]["TradeInsightAiMetricCard"][];
            /** Reason */
            reason: string;
            /** Signal */
            signal: string;
            /** Summary */
            summary: string;
            /** Title */
            title: string;
        };
        /** TradeInsightsHeader */
        TradeInsightsHeader: {
            /**
             * Badges
             * @default []
             */
            badges: components["schemas"]["InsightBadge"][];
            /**
             * Confidence Label
             * @default LOW
             */
            confidence_label: string;
            /**
             * Data Quality Label
             * @default INSUFFICIENT
             */
            data_quality_label: string;
            /**
             * Dominant Bias
             * @default NEUTRAL
             */
            dominant_bias: string;
            /**
             * Idea Count
             * @default 0
             */
            idea_count: number;
            /** Preferred Idea Id */
            preferred_idea_id?: string | null;
            /**
             * Primary Setup
             * @default NO_CLEAR_SETUP
             */
            primary_setup: string;
        };
        /** TradeInsightsResponse */
        TradeInsightsResponse: {
            /** As Of */
            as_of?: string | null;
            /**
             * Candidate Structures
             * @default []
             */
            candidate_structures: components["schemas"]["CandidateStructure"][];
            /**
             * Flow Table
             * @default []
             */
            flow_table: components["schemas"]["ChainFlowReadRow"][];
            header: components["schemas"]["TradeInsightsHeader"];
            /**
             * Mode
             * @default research
             */
            mode: string;
            /**
             * Signal Stack
             * @default []
             */
            signal_stack: components["schemas"]["InsightSignalRow"][];
            /**
             * @default {
             *       "decision": "Use deterministic data only where source agreement is understood.",
             *       "headline": "Source reconciliation unavailable",
             *       "rows": [],
             *       "status": "UNKNOWN"
             *     }
             */
            source_reconciliation: components["schemas"]["SourceReconciliation"];
            /**
             * @default {
             *       "avoid": [],
             *       "dominant_story": "",
             *       "required_before_sizing": []
             *     }
             */
            synthesis: components["schemas"]["InsightsSynthesis"];
            /**
             * Term Structure Table
             * @default []
             */
            term_structure_table: components["schemas"]["TermMoveRow"][];
            /** Ticker */
            ticker: string;
        };
        /** TradePlan */
        TradePlan: {
            /** Direction */
            direction: string;
            /**
             * Legs
             * @default []
             */
            legs: components["schemas"]["TradePlanLeg"][];
            /** Max Loss */
            max_loss?: string | null;
            /** Max Profit */
            max_profit?: string | null;
            /** Rationale */
            rationale: string;
            /** Structure */
            structure: string;
        };
        /** TradePlanLeg */
        TradePlanLeg: {
            /**
             * Expiry
             * Format: date
             */
            expiry: string;
            /** Mid */
            mid?: string | null;
            /** Option Symbol */
            option_symbol: string;
            /** Side */
            side: string;
            /** Strike */
            strike: string;
        };
        /** VRPAssessment */
        VRPAssessment: {
            /** Note */
            note: string;
            /** Signal */
            signal: string;
            /** Vrp */
            vrp?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VolHeaderBlock */
        VolHeaderBlock: {
            /** Implied Move 30D Perc */
            implied_move_30d_perc?: string | null;
            /** Iv */
            iv?: string | null;
            /** Iv High 52W */
            iv_high_52w?: string | null;
            /** Iv Low 52W */
            iv_low_52w?: string | null;
            /** Iv Percentile 30D */
            iv_percentile_30d?: string | null;
            /** Iv Rank */
            iv_rank?: string | null;
            /** Iv Rank 1Y */
            iv_rank_1y?: string | null;
            /** Rv */
            rv?: string | null;
            /** Rv High 52W */
            rv_high_52w?: string | null;
            /** Rv Low 52W */
            rv_low_52w?: string | null;
            /** Skew 25D */
            skew_25d?: string | null;
            /** Vrp */
            vrp?: string | null;
            /**
             * Vrp Note
             * @default
             */
            vrp_note: string;
            /**
             * Vrp Signal
             * @default
             */
            vrp_signal: string;
        };
        /** VolatilityProfile */
        VolatilityProfile: {
            /** Implied Move 30D Perc */
            implied_move_30d_perc?: string | null;
            /** Iv */
            iv?: string | null;
            /** Iv High 52W */
            iv_high_52w?: string | null;
            /** Iv Low 52W */
            iv_low_52w?: string | null;
            /** Iv Percentile 30D */
            iv_percentile_30d?: string | null;
            /** Iv Rank */
            iv_rank?: string | null;
            /** Iv Rank 1Y */
            iv_rank_1y?: string | null;
            /** Rv */
            rv?: string | null;
            /** Rv High 52W */
            rv_high_52w?: string | null;
            /** Rv Low 52W */
            rv_low_52w?: string | null;
            /** Skew 25D */
            skew_25d?: string | null;
            /**
             * Term Dte To Iv
             * @default []
             */
            term_dte_to_iv: [
                number,
                string
            ][];
        };
        /** VolatilitySeriesResponse */
        VolatilitySeriesResponse: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Backfill Status */
            backfill_status: string;
            /**
             * Divergence
             * @default []
             */
            divergence: components["schemas"]["DivergencePoint"][];
            /**
             * Divergence Headline
             * @default
             */
            divergence_headline: string;
            header: components["schemas"]["VolHeaderBlock"];
            /**
             * Hv Iv History
             * @default []
             */
            hv_iv_history: components["schemas"]["IvHvPoint"][];
            /**
             * Iv Of Iv
             * @default []
             */
            iv_of_iv: components["schemas"]["IvOfIvPoint"][];
            /**
             * @default {
             *       "bins": []
             *     }
             */
            iv_percentile_distribution: components["schemas"]["IvPercentileDistribution"];
            /**
             * @default {
             *       "points": []
             *     }
             */
            regime_quadrant: components["schemas"]["RegimeQuadrantBlock"];
            /**
             * Rv Spy Corr
             * @default []
             */
            rv_spy_corr: components["schemas"]["RvCorrPoint"][];
            /**
             * Smile
             * @default []
             */
            smile: components["schemas"]["SmileExpiryCurve"][];
            /** Spot */
            spot?: string | null;
            /**
             * Term Structure
             * @default []
             */
            term_structure: components["schemas"]["TermStructureExpiryRow"][];
            /** Ticker */
            ticker: string;
            /**
             * Vrp Spread
             * @default []
             */
            vrp_spread: components["schemas"]["VrpDailyPoint"][];
            /**
             * Vrp Spread Headline
             * @default
             */
            vrp_spread_headline: string;
        };
        /** VrpDailyPoint */
        VrpDailyPoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Vrp */
            vrp?: string | null;
            /** Vrp Z 20 */
            vrp_z_20?: string | null;
        };
        /** WatchlistCard */
        WatchlistCard: {
            /** Aggression Pct */
            aggression_pct?: string | null;
            gamma: components["schemas"]["GammaBlock"];
            /** Iv Atm */
            iv_atm?: string | null;
            /** Iv Rank */
            iv_rank?: string | null;
            /** Pinned */
            pinned: boolean;
            positioning: components["schemas"]["PositioningBlock"];
            queue?: components["schemas"]["QueueStatus"] | null;
            returns: components["schemas"]["ReturnsBlock"];
            /** Scanned At */
            scanned_at?: string | null;
            /** Sector */
            sector: string;
            setup: components["schemas"]["SetupBlock"];
            skew: components["schemas"]["SkewBlock"];
            /** Sort Rank */
            sort_rank: number;
            /** Spot */
            spot?: string | null;
            /** Spot Quoted At */
            spot_quoted_at?: string | null;
            /** Spot Source */
            spot_source?: string | null;
            /** Ticker */
            ticker: string;
        };
        /** WatchlistMutation */
        WatchlistMutation: {
            /** Notes */
            notes?: string | null;
            /**
             * Pinned
             * @default false
             */
            pinned: boolean;
            /** Sector */
            sector: string;
            /**
             * Sort Rank
             * @default 0
             */
            sort_rank: number;
            /** Ticker */
            ticker: string;
        };
        /** WatchlistPatch */
        WatchlistPatch: {
            /** Notes */
            notes?: string | null;
            /** Pinned */
            pinned?: boolean | null;
            /** Sector */
            sector?: string | null;
            /** Sort Rank */
            sort_rank?: number | null;
        };
        /** WatchlistResponse */
        WatchlistResponse: {
            queue?: components["schemas"]["QueueSummary"];
            /** Scanned At Max */
            scanned_at_max?: string | null;
            /** Scanned At Min */
            scanned_at_min?: string | null;
            /** Scheduler Lag Seconds */
            scheduler_lag_seconds?: number | null;
            /** Tickers */
            tickers: components["schemas"]["WatchlistCard"][];
        };
        /** WorkerHealth */
        WorkerHealth: {
            /** Heartbeat Name */
            heartbeat_name: string;
            /** Index */
            index: number;
            /** Label */
            label: string;
            /** Lag Seconds */
            lag_seconds?: number | null;
            /** Last Beat At */
            last_beat_at?: string | null;
            /**
             * Role
             * @enum {string}
             */
            role: "uw" | "massive";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: {
                source?: "uw" | "massive";
                record_window_hours?: number | null;
                record_min_coverage?: number;
                record_tables?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ohlc_api_ohlc__ticker__get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OhlcRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    provider_usage_endpoints_api_provider_usage_endpoints_get: {
        parameters: {
            query?: {
                provider?: "uw" | "massive" | "all";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderUsageBreakdownResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    provider_usage_requests_api_provider_usage_requests_get: {
        parameters: {
            query?: {
                provider?: "uw" | "massive" | "all";
                ticker?: string | null;
                status_family?: ("2xx" | "3xx" | "4xx" | "5xx" | "transport_error") | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderUsageRequestsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    provider_usage_summary_api_provider_usage_summary_get: {
        parameters: {
            query?: {
                provider?: "uw" | "massive" | "all";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderUsageSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    provider_usage_tickers_api_provider_usage_tickers_get: {
        parameters: {
            query?: {
                provider?: "uw" | "massive" | "all";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderUsageBreakdownResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stock_api_stock__ticker__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SingleStockReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stock_history_api_stock__ticker__history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_stock__ticker__runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_specific_run_api_stock__ticker__runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SingleStockReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trade_insights_api_stock__ticker__trade_insights_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeInsightsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_trade_insights_ai_analysis_api_stock__ticker__trade_insights_ai_analysis_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["TradeInsightAiAnalysisRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeInsightAiAnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_latest_trade_insights_ai_analysis_api_stock__ticker__trade_insights_ai_analysis_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeInsightAiAnalysisResponse"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trade_insights_ai_analysis_api_stock__ticker__trade_insights_ai_analysis__analysis_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeInsightAiAnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_volatility_series_api_stock__ticker__volatility_series_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VolatilitySeriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_watchlist_api_watchlist_get: {
        parameters: {
            query?: {
                sector?: string | null;
                /** @description e.g. 'C-bull', 'C-bear', 'F-MULTI', 'NEUTRAL' */
                setup?: string | null;
                fresh_within_minutes?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_watchlist_api_watchlist_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistMutation"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enqueue_rescan_all_api_watchlist_rescan_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RescanAllRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_watchlist_api_watchlist__ticker__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_watchlist_api_watchlist__ticker__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enqueue_rescan_api_watchlist__ticker__rescan_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
