"""Self-contained snapshot test for the markdown renderer.

Hand-crafted fixture (12 rows spanning all four levels) — does NOT depend on
any on-disk artifact. The renderer is a pure function over (run, daily);
this test pins its contract independently of the backtest's empirical scale.

Why score-derived levels: the renderer's level-distribution table uses
`_cri_level(score)` (see renderer docstring), not the row-level `level`
column. The scores below map to:
    LOW       (score <  25)  -> 3 rows
    ELEVATED  (25 <= s < 50) -> 3 rows
    HIGH      (50 <= s < 75) -> 3 rows
    CRITICAL  (s >= 75)      -> 3 rows
"""

from __future__ import annotations

from datetime import date

from uw_scan.reports.regime_backtest_report import render_backtest_markdown


def _make_daily() -> list[dict]:
    scores = [10.0, 15.0, 20.0, 30.0, 40.0, 45.0, 55.0, 65.0, 70.0, 80.0, 85.0, 90.0]
    return [
        {
            "trade_date": date(2024, 1, 2 + i),
            "score": s,
            # row-level `level` is intentionally NOT consistent with _cri_level
            # for two rows — the renderer must ignore this column for the
            # distribution table (it uses _cri_level(score) instead).
            "level": "ELEVATED",
            "payload": {"fired": s >= 75.0},
        }
        for i, s in enumerate(scores)
    ]


# Markdown hard-line-break = two trailing spaces before \n. Built via string
# concatenation so formatters that strip trailing whitespace can't munge it.
_HARD_BREAK = "  \n"

EXPECTED_MD = (
    "# CRI Backtest — 2006-2026\n"
    "\n"
    "Generated by `scripts/backtest_cri.py`. "
    "Re-run after any calibration change.\n"
    "\n"
    f"**N days:** 12{_HARD_BREAK}"
    "**Date range:** 2024-01-02 → 2024-01-13\n"
    "\n"
    "## Score distribution\n"
    "\n"
    "| Stat | Value |\n"
    "|---|---|\n"
    "| mean | 50.42 |\n"
    "| min | 10.00 |\n"
    "| p25 | 27.50 |\n"
    "| p50 | 50.00 |\n"
    "| p75 | 72.50 |\n"
    "| p90 | 84.50 |\n"
    "| p95 | 87.25 |\n"
    "| p99 | 89.45 |\n"
    "| max | 90.00 |\n"
    "\n"
    "## Level distribution\n"
    "\n"
    "| Level | Count | % |\n"
    "|---|---|---|\n"
    "| LOW | 3 | 25.0% |\n"
    "| ELEVATED | 3 | 25.0% |\n"
    "| HIGH | 3 | 25.0% |\n"
    "| CRITICAL | 3 | 25.0% |\n"
    "\n"
    "## Named crash dates\n"
    "\n"
    "| Date | Event | CRI score | Level | Trigger fired |\n"
    "|---|---|---|---|---|\n"
    "| _no aligned data for any named date_ | | | | |\n"
)


def test_render_produces_expected_markdown_from_synthetic_rows() -> None:
    daily = _make_daily()
    run = {
        "indicator": "cri",
        "composite_version": "3",
        "start_date": date(2023, 6, 1),
        "end_date": daily[-1]["trade_date"],
        "window_days": 150,
        "n_days": len(daily),
        "summary": {"oos": None, "extras": {}},
    }
    actual = render_backtest_markdown(run, daily)
    assert actual == EXPECTED_MD, (
        "renderer drift:\n--- expected ---\n"
        + EXPECTED_MD
        + "\n--- actual ---\n"
        + actual
    )


def test_render_empty_daily_returns_placeholder() -> None:
    run = {
        "indicator": "cri",
        "composite_version": "3",
        "start_date": date(2024, 1, 1),
        "end_date": date(2024, 1, 1),
        "window_days": 150,
        "n_days": 0,
        "summary": {"oos": None, "extras": {}},
    }
    assert (
        render_backtest_markdown(run, [])
        == "# CRI Backtest\n\n_No daily rows available._\n"
    )
