import type { TradeInsightsAiAnalysisResponse } from "@/lib/api";
import { InsightStatusBanner } from "../InsightPanel";
import { OutcomeHeader } from "./OutcomeHeader";
import { SectionCardsGrid } from "./SectionCardsGrid";
import { type Tone, shortDate } from "./ui";
import {
  type PromptMetadata,
  type Provider,
  isInFlight,
} from "./useAiAnalysisPolling";

type Outcome = NonNullable<TradeInsightsAiAnalysisResponse["outcome"]>;

function toneFromText(value: string | null | undefined): Tone {
  const text = (value ?? "").toLowerCase();
  if (
    text.includes("bull") ||
    text.includes("buy") ||
    text.includes("positive") ||
    text.includes("break")
  ) {
    return "positive";
  }
  if (
    text.includes("bear") ||
    text.includes("sell") ||
    text.includes("negative") ||
    text.includes("blocked") ||
    text.includes("failed")
  ) {
    return "negative";
  }
  if (
    text.includes("wait") ||
    text.includes("mixed") ||
    text.includes("check") ||
    text.includes("risk")
  ) {
    return "warning";
  }
  return "neutral";
}

function providerLabel(p: Provider): string {
  return p.charAt(0).toUpperCase() + p.slice(1);
}

function isLegacyAnalysis(
  analysis: TradeInsightsAiAnalysisResponse | null,
  currentPromptVersion: string,
): boolean {
  if (!analysis) return false;
  if (analysis.status !== "succeeded") return false;
  if (!currentPromptVersion) return false;
  // The v5 API-side legacy guard (_row_to_ai_response) drops outcome to null
  // when the row's prompt_version differs from the current PROMPT_VERSION,
  // so we recognize a legacy row by the (succeeded + null outcome +
  // prompt_version mismatch) signature.
  return (
    analysis.outcome == null &&
    analysis.prompt_version !== currentPromptVersion
  );
}

function currentPromptDisplay(metadata: PromptMetadata): string {
  return (
    metadata.current_prompt_label ||
    metadata.current_prompt_version ||
    "current prompt"
  );
}

function OutcomeGrid({
  outcome,
  provider,
}: {
  outcome: Outcome;
  provider: Provider;
}) {
  return (
    <div style={{ display: "grid", gap: 14 }}>
      <OutcomeHeader
        outcome={outcome}
        provider={provider}
        providerLabel={providerLabel}
      />
      <SectionCardsGrid outcome={outcome} toneFromText={toneFromText} />
    </div>
  );
}

export function ProviderTabBody({
  provider,
  analysis,
  pending,
  promptMetadata,
}: {
  provider: Provider;
  analysis: TradeInsightsAiAnalysisResponse | null;
  pending: boolean;
  promptMetadata: PromptMetadata;
}) {
  const succeeded = analysis?.status === "succeeded" && analysis.outcome;
  const failed = analysis?.status === "failed";
  const legacy = isLegacyAnalysis(
    analysis,
    promptMetadata.current_prompt_version,
  );
  return (
    <div style={{ display: "grid", gap: 12 }}>
      {pending && (
        <InsightStatusBanner
          text={`${providerLabel(provider)} is running…`}
          severity="info"
        />
      )}
      {analysis && isInFlight(analysis) && !pending && (
        <InsightStatusBanner
          text={`${providerLabel(provider)} ${analysis.status}`}
          severity="info"
        />
      )}
      {failed && (
        <InsightStatusBanner
          text={analysis?.error_message ?? `${providerLabel(provider)} failed`}
          severity="negative"
        />
      )}
      {legacy && (
        <InsightStatusBanner
          text={
            `Legacy analysis (${analysis?.prompt_version}). Schema bumped ` +
            `to ${currentPromptDisplay(promptMetadata)} — click Run to ` +
            `regenerate with the current prompt contract.`
          }
          severity="warning"
        />
      )}
      {succeeded && analysis.outcome && (
        <OutcomeGrid outcome={analysis.outcome} provider={provider} />
      )}
      {!analysis && !pending && (
        <div
          style={{
            color: "var(--text-secondary)",
            fontSize: 12,
            padding: 12,
            border: "1px dashed var(--border-dim)",
            borderRadius: 4,
          }}
        >
          No analysis yet for {providerLabel(provider)}. Click Run to generate.
        </div>
      )}
      {analysis?.status === "succeeded" && (
        <div
          style={{
            color: "var(--text-muted)",
            fontSize: 10,
            fontFamily: "var(--font-mono)",
            letterSpacing: 0.5,
          }}
        >
          Generated by {providerLabel(provider)} ({analysis.model}) · prompt{" "}
          {analysis.prompt_version} ·{" "}
          {shortDate(analysis.produced_at ?? analysis.finished_at)}
        </div>
      )}
    </div>
  );
}
