"""Pure renderer: regime_backtest_runs row + daily rows -> markdown.

Extracted from scripts/backtest_cri.py's legacy write_report(). The router
calls this on each /api/regime/validation request — no I/O, no DB, no state.

Window-start contract: the "Date range" line uses daily[0].trade_date, NOT
run.start_date. The script's rolling_compute skips the first 150 sessions
(`window=150` lookback), so run.start_date predates the first emitted row
by ~7 months of trading days. Snapshot tests rely on this.
"""

from __future__ import annotations

from collections import Counter
from io import StringIO
from typing import Any

import numpy as np

from uw_scan.cards.cri_scorers import cri_level as _cri_level

# Named crash events that appear in the report. Keep in sync with
# scripts/backtest_cri.py:NAMED_CRASH_DATES — the source of truth for the
# event labels lives in the script that produces the data.
NAMED_CRASH_DATES: dict[str, str] = {
    "2008-09-15": "Lehman bankruptcy",
    "2008-10-10": "GFC bottom area",
    "2010-05-06": "Flash crash",
    "2011-08-08": "US credit downgrade",
    "2015-08-24": "Black Monday (China)",
    "2018-02-05": "Volmageddon",
    "2018-12-24": "Q4 selloff trough",
    "2020-02-28": "COVID early break",
    "2020-03-16": "COVID circuit breaker",
    "2022-06-13": "Rate-hike vol",
    "2024-08-05": "Yen-carry unwind",
}

_LEVELS = ("LOW", "ELEVATED", "HIGH", "CRITICAL")


def _summarize(scores: list[float]) -> dict[str, Any]:
    """Distribution stats + score-derived level counts.

    `level_counts` is derived from `_cri_level(score)` (NOT from the daily
    row's `level` column) — this matches the legacy write_report() behavior
    where the level table was an aggregate of the score-band function, not
    the row-level interpretation. The two differ on ~10 boundary cases out
    of 4873 because the row-level `level` may carry extra context from the
    full payload at scan time.
    """
    arr = np.array(scores, dtype=float)
    return {
        "n": int(arr.size),
        "mean": float(arr.mean()),
        "min": float(arr.min()),
        "max": float(arr.max()),
        "p25": float(np.percentile(arr, 25)),
        "p50": float(np.percentile(arr, 50)),
        "p75": float(np.percentile(arr, 75)),
        "p90": float(np.percentile(arr, 90)),
        "p95": float(np.percentile(arr, 95)),
        "p99": float(np.percentile(arr, 99)),
        "level_counts": dict(Counter(_cri_level(s) for s in scores)),
    }


def render_backtest_markdown(run: dict, daily: list[dict]) -> str:
    """Reproduce the legacy cri-backtest.md format from a run row + daily rows.

    `run` is a dict from RegimeBacktestRepository.find_latest_run (or any row
    matching the regime_backtest_runs columns).
    `daily` is a list of dicts with at minimum {trade_date, score, level,
    payload}. payload may carry `fired` (CRI) and indicator-specific extras.
    """
    if not daily:
        return "# CRI Backtest\n\n_No daily rows available._\n"

    scores = [float(d["score"]) for d in daily]
    summary = _summarize(scores)

    by_iso = {d["trade_date"].isoformat(): d for d in daily}

    out = StringIO()
    out.write("# CRI Backtest — 2006-2026\n\n")
    out.write(
        "Generated by `scripts/backtest_cri.py`. "
        "Re-run after any calibration change.\n\n"
    )
    out.write(f"**N days:** {summary['n']}  \n")
    out.write(
        f"**Date range:** {daily[0]['trade_date'].isoformat()} "
        f"→ {daily[-1]['trade_date'].isoformat()}\n\n"
    )

    out.write("## Score distribution\n\n")
    out.write("| Stat | Value |\n|---|---|\n")
    for k in ("mean", "min", "p25", "p50", "p75", "p90", "p95", "p99", "max"):
        out.write(f"| {k} | {summary[k]:.2f} |\n")

    out.write("\n## Level distribution\n\n")
    out.write("| Level | Count | % |\n|---|---|---|\n")
    total = summary["n"]
    for lvl in _LEVELS:
        count = summary["level_counts"].get(lvl, 0)
        out.write(f"| {lvl} | {count} | {count / total * 100:.1f}% |\n")

    out.write("\n## Named crash dates\n\n")
    out.write("| Date | Event | CRI score | Level | Trigger fired |\n")
    out.write("|---|---|---|---|---|\n")
    hits = 0
    for iso, name in NAMED_CRASH_DATES.items():
        row = by_iso.get(iso)
        if row is None:
            continue
        hits += 1
        fired = bool((row.get("payload") or {}).get("fired", False))
        out.write(
            f"| {iso} | {name} | {float(row['score']):.1f} | {row['level']} | {fired} |\n"
        )
    if hits == 0:
        out.write("| _no aligned data for any named date_ | | | | |\n")
    return out.getvalue()
