from __future__ import annotations

from datetime import date, datetime, timezone
from decimal import Decimal

from .analysis import build_stock_analysis, sample_tsla_analysis_inputs
from .models import (
    DashboardViewModel,
    FlowRow,
    Opportunity,
    RequestBudgetSummary,
    SignalDirection,
    SnapshotSummary,
    SourceFeed,
    SourceKind,
    StructureIdea,
    SurfaceMetric,
    TrackedItem,
    WatchlistSourceView,
)


def demo_dashboard() -> DashboardViewModel:
    generated_at = datetime(2026, 5, 11, 13, 30, tzinfo=timezone.utc)
    tv_source = SourceFeed(
        label="portfolio(update daily)",
        kind=SourceKind.TRADINGVIEW,
        url="https://www.tradingview.com/watchlists/326877343/",
        status="degraded: sample page did not expose symbols in static or rendered validation",
    )
    uw_source = SourceFeed(label="UW Flow Poll", kind=SourceKind.UW_FLOW, status="ready")

    return DashboardViewModel(
        generated_at_utc=generated_at,
        opportunities=[
            Opportunity(
                ticker="NVDA",
                contract_label="NVDA 2026-06-19 650C",
                direction=SignalDirection.BULLISH,
                score=5,
                setup_types=["Deep Conviction Directional", "Multi-Signal Confluence"],
                confirmations=["Ask-side premium", "Volume > OI", "IV rising"],
                warnings=["Next-session OI pending"],
                source_labels=[uw_source.label],
                structure_idea=StructureIdea(
                    structure_type="Call debit spread candidate",
                    rationale="Bullish ask-side flow with high conviction and IV expansion.",
                    invalidation="Downgrade if next-session OI does not confirm or skew turns strongly bearish.",
                ),
            ),
            Opportunity(
                ticker="TSLA",
                contract_label="TSLA $385/$400C Apr17 spread",
                direction=SignalDirection.BULLISH,
                score=5,
                setup_types=["Breakout Through Gamma Wall", "Cheap IV Directional"],
                confirmations=["+$524M net premium", "IV rank 3.4", "Bullish OI above $385"],
                warnings=["$382.50 GEX wall may cap immediate upside"],
                source_labels=[uw_source.label],
                structure_idea=StructureIdea(
                    structure_type="Bull call spread candidate",
                    rationale="Cheap IV and bullish flow favor defined-risk call exposure above the $382.50 wall.",
                    invalidation="Close if TSLA loses $370 support or fails to break $382.50 with volume.",
                ),
            ),
            Opportunity(
                ticker="AMD",
                contract_label="AMD important expiries",
                direction=SignalDirection.BULLISH,
                score=4,
                setup_types=["Watchlist Confluence", "OI Buildup"],
                confirmations=["TradingView source", "Call OI building", "Max pain below spot"],
                warnings=["Needs live UW refresh"],
                source_labels=[tv_source.label],
                structure_idea=StructureIdea(
                    structure_type="Call spread watch",
                    rationale="Watchlist name with call-side concentration near important tenor.",
                    invalidation="Avoid if liquidity is thin or OI build reverses.",
                ),
            ),
            Opportunity(
                ticker="AAPL",
                contract_label="AAPL 2026-06-19 240C",
                direction=SignalDirection.BULLISH,
                score=4,
                setup_types=["Opening Call Sweep", "IV Rank Expansion"],
                confirmations=["Sweep volume", "OI confirmation pending", "IV rank rising"],
                warnings=["Premium is concentrated in one expiry"],
                source_labels=[uw_source.label, tv_source.label],
                structure_idea=StructureIdea(
                    structure_type="Call calendar candidate",
                    rationale="Short-term call demand with IV expansion favors defined-risk upside participation.",
                    invalidation="Avoid if call OI does not expand on the next update.",
                ),
            ),
            Opportunity(
                ticker="MSFT",
                contract_label="MSFT 2026-09-18 520C",
                direction=SignalDirection.BULLISH,
                score=3,
                setup_types=["Watchlist Confluence", "Term Structure Support"],
                confirmations=["TradingView source", "Longer tenor call OI", "Realized vol below implied"],
                warnings=["Needs fresh flow confirmation"],
                source_labels=[tv_source.label],
                structure_idea=StructureIdea(
                    structure_type="Call spread watch",
                    rationale="Watchlist ticker with supportive term structure but no fresh high-conviction flow yet.",
                    invalidation="Wait for ask-side flow or OI acceleration.",
                ),
            ),
            Opportunity(
                ticker="SMCI",
                contract_label="SMCI 2026-06-19 110C",
                direction=SignalDirection.NEUTRAL,
                score=3,
                setup_types=["High IV Event Risk", "Liquidity Warning"],
                confirmations=["Elevated IV rank", "Wide expected move"],
                warnings=["Spread width is high", "Avoid oversized directional reads"],
                source_labels=[tv_source.label],
                structure_idea=StructureIdea(
                    structure_type="Defined-risk iron condor candidate",
                    rationale="High IV and event risk favor a defined-risk structure if liquidity improves.",
                    invalidation="Skip if bid/ask width remains too wide.",
                ),
            ),
        ],
        flow_rows=[
            FlowRow(
                ticker="NVDA",
                option_symbol="NVDA260619C00650000",
                expiry=date(2026, 6, 19),
                strike=Decimal("650"),
                option_type="call",
                premium=Decimal("1250000"),
                volume=2400,
                open_interest=900,
                side="ask",
                dte=39,
                source_label=uw_source.label,
            ),
            FlowRow(
                ticker="TSLA",
                option_symbol="TSLA260417C00385000",
                expiry=date(2026, 4, 17),
                strike=Decimal("385"),
                option_type="call",
                premium=Decimal("524300000"),
                volume=136564,
                open_interest=56586,
                side="ask",
                dte=24,
                source_label=uw_source.label,
            ),
            FlowRow(
                ticker="AMD",
                option_symbol="AMD260619C00210000",
                expiry=date(2026, 6, 19),
                strike=Decimal("210"),
                option_type="call",
                premium=Decimal("640000"),
                volume=3100,
                open_interest=1450,
                side="ask",
                dte=39,
                source_label=uw_source.label,
            ),
            FlowRow(
                ticker="AAPL",
                option_symbol="AAPL260619C00240000",
                expiry=date(2026, 6, 19),
                strike=Decimal("240"),
                option_type="call",
                premium=Decimal("710000"),
                volume=1700,
                open_interest=690,
                side="ask",
                dte=39,
                source_label=uw_source.label,
            ),
            FlowRow(
                ticker="MSFT",
                option_symbol="MSFT260918C00520000",
                expiry=date(2026, 9, 18),
                strike=Decimal("520"),
                option_type="call",
                premium=Decimal("520000"),
                volume=950,
                open_interest=2400,
                side="mid",
                dte=130,
                source_label=uw_source.label,
            ),
            FlowRow(
                ticker="SMCI",
                option_symbol="SMCI260619C00110000",
                expiry=date(2026, 6, 19),
                strike=Decimal("110"),
                option_type="call",
                premium=Decimal("430000"),
                volume=1250,
                open_interest=500,
                side="ask",
                dte=39,
                source_label=uw_source.label,
            ),
        ],
        watchlist_sources=[
            WatchlistSourceView(
                source=tv_source,
                imported_symbols=["AAPL", "AMD", "MSFT", "NVDA", "SMCI", "TSLA"],
                failed_symbols=[],
                parsed_at_utc=generated_at,
            )
        ],
        tracked_items=[
            TrackedItem(
                label="NVDA 650C Jun19",
                ticker="NVDA",
                option_symbol="NVDA260619C00650000",
                expiry=date(2026, 6, 19),
                tracking_kind="contract",
                reconciliation_status="next OI pending",
                iv_change=Decimal("0.035"),
                oi_change=None,
            )
            ,
            TrackedItem(
                label="TSLA 385C Apr17",
                ticker="TSLA",
                option_symbol="TSLA260417C00385000",
                expiry=date(2026, 4, 17),
                tracking_kind="contract",
                reconciliation_status="likely_opening",
                iv_change=Decimal("0.047"),
                oi_change=420,
            ),
            TrackedItem(
                label="AMD Jun19 call tenor",
                ticker="AMD",
                option_symbol=None,
                expiry=date(2026, 6, 19),
                tracking_kind="expiry_tenor",
                reconciliation_status="watching OI buildup",
                iv_change=Decimal("0.021"),
                oi_change=1350,
            ),
            TrackedItem(
                label="AAPL 240C Jun19",
                ticker="AAPL",
                option_symbol="AAPL260619C00240000",
                expiry=date(2026, 6, 19),
                tracking_kind="contract",
                reconciliation_status="OI confirmation pending",
                iv_change=Decimal("0.018"),
                oi_change=None,
            ),
        ],
        surface_metrics=[
            SurfaceMetric(
                ticker="NVDA",
                expiry=date(2026, 6, 19),
                strike=Decimal("650"),
                call_iv=Decimal("0.54"),
                put_iv=Decimal("0.58"),
                gamma_exposure=Decimal("1250000"),
                delta_exposure=Decimal("4800000"),
                vanna_exposure=Decimal("220000"),
                charm_exposure=Decimal("-180000"),
            ),
            SurfaceMetric(
                ticker="TSLA",
                expiry=date(2026, 4, 17),
                strike=Decimal("382.50"),
                call_iv=Decimal("0.402"),
                put_iv=Decimal("0.416"),
                gamma_exposure=Decimal("100400000"),
                delta_exposure=Decimal("152500000"),
                vanna_exposure=Decimal("400000"),
                charm_exposure=Decimal("0"),
            ),
            SurfaceMetric(
                ticker="AMD",
                expiry=date(2026, 6, 19),
                strike=Decimal("210"),
                call_iv=Decimal("0.49"),
                put_iv=Decimal("0.52"),
                gamma_exposure=Decimal("780000"),
                delta_exposure=Decimal("2100000"),
                vanna_exposure=Decimal("170000"),
                charm_exposure=Decimal("-65000"),
            ),
            SurfaceMetric(
                ticker="AAPL",
                expiry=date(2026, 6, 19),
                strike=Decimal("240"),
                call_iv=Decimal("0.31"),
                put_iv=Decimal("0.34"),
                gamma_exposure=Decimal("510000"),
                delta_exposure=Decimal("1650000"),
                vanna_exposure=Decimal("85000"),
                charm_exposure=Decimal("-41000"),
            ),
        ],
        stock_analyses=[build_stock_analysis(sample_tsla_analysis_inputs())],
        snapshots=[
            SnapshotSummary(
                run_id="fixture-20260511-1330",
                mode="fixture",
                started_at_utc=generated_at,
                source_count=2,
                opportunity_count=2,
            )
        ],
        request_budget=RequestBudgetSummary(
            flow_rows=100,
            watchlist_symbols=6,
            estimated_discovery_requests=2,
            estimated_enrichment_requests=72,
            estimated_deep_surface_requests=24,
            total_estimated_requests=98,
            max_requests_per_cycle=250,
            capped=False,
        ),
    )
