-- 006_seed_watchlist.sql — seed the canonical watchlist with the 54-ticker default.
-- Idempotent: ON CONFLICT (ticker) DO NOTHING so re-running is safe.

SET search_path TO uw_scan, public;

INSERT INTO uw_scan.watchlist (ticker, sector, notes, sort_rank) VALUES
  ('AAPL',  'Technology',              'M7', 1),
  ('MSFT',  'Technology',              'M7', 2),
  ('NVDA',  'Technology',              'M7', 3),
  ('AMZN',  'Consumer Discretionary',  'M7', 4),
  ('META',  'Communication Services',  'M7', 5),
  ('GOOGL', 'Communication Services',  'M7', 6),
  ('TSLA',  'Consumer Discretionary',  'M7', 7),
  ('AMD',   'Technology',              'Semiconductor', 10),
  ('AVGO',  'Technology',              'Semiconductor', 11),
  ('INTC',  'Technology',              'Semiconductor', 12),
  ('MU',    'Technology',              'Semiconductor — memory', 13),
  ('MRVL',  'Technology',              'Semiconductor — custom silicon', 14),
  ('TSM',   'Technology',              'Semiconductor — foundry', 15),
  ('QCOM',  'Technology',              'Semiconductor — mobile', 16),
  ('CRWV',  'Technology',              'Semiconductor — AI inference', 17),
  ('NBIS',  'Technology',              'Semiconductor — data center', 18),
  ('IREN',  'Technology',              'Semiconductor — data center / mining', 19),
  ('CRDO',  'Technology',              'Semiconductor — connectivity', 20),
  ('SNDK',  'Technology',              'Semiconductor — storage', 21),
  ('LITE',  'Technology',              'Semiconductor — photonics', 22),
  ('GLW',   'Technology',              'Semiconductor — optical fiber', 23),
  ('NOK',   'Technology',              'Semiconductor — telecom infra', 24),
  ('TSEM',  'Technology',              'Semiconductor — foundry', 25),
  ('PLTR',  'Technology',              'Growth / tech — data analytics', 30),
  ('HIMS',  'Healthcare',              'Growth / tech — telehealth', 31),
  ('HOOD',  'Financials',              'Growth / tech — fintech', 32),
  ('SOFI',  'Financials',              'Growth / tech — fintech', 33),
  ('ASTS',  'Communication Services',  'Growth / tech — satellite', 34),
  ('RKLB',  'Industrials',             'Growth / tech — space', 35),
  ('NET',   'Technology',              'Growth / tech — cloud infra', 36),
  ('PANW',  'Technology',              'Growth / tech — cybersecurity', 37),
  ('BKSY',  'Technology',              'Growth / tech — geospatial', 38),
  ('KO',    'Consumer Staples',        'Industrials / value', 40),
  ('MCD',   'Consumer Discretionary',  'Industrials / value', 41),
  ('LLY',   'Healthcare',              'Industrials / value — pharma', 42),
  ('JPM',   'Financials',              'Industrials / value — bank', 43),
  ('GS',    'Financials',              'Industrials / value — bank', 44),
  ('BA',    'Industrials',             'Industrials / value — aerospace', 45),
  ('COST',  'Consumer Staples',        'Industrials / value — retail', 46),
  ('WMT',   'Consumer Staples',        'Industrials / value — retail', 47),
  ('MS',    'Financials',              'Industrials / value — bank', 48),
  ('DAL',   'Industrials',             'Industrials / value — airline', 49),
  ('XOM',   'Energy',                  'Industrials / value — energy', 50),
  ('OXY',   'Energy',                  'Industrials / value — energy', 51),
  ('CVX',   'Energy',                  'Industrials / value — energy', 52),
  ('CRS',   'Industrials',             'Industrials / value — specialty alloys', 53),
  ('FLY',   'Industrials',             'Industrials / value — aircraft leasing', 54),
  ('PL',    'Technology',              'Industrials / value — satellite imaging', 55),
  ('COIN',  'Financials',              'Crypto proxy', 60),
  ('MSTR',  'Technology',              'Crypto proxy — BTC treasury', 61),
  ('CRCL',  'Financials',              'Crypto proxy — USDC issuer', 62),
  ('SPY',   'ETF',                     'Broad market ETF', 70),
  ('QQQ',   'ETF',                     'Nasdaq 100 ETF', 71),
  ('IWM',   'ETF',                     'Russell 2000 ETF', 72)
ON CONFLICT (ticker) DO NOTHING;
