-- 006_seed_watchlist.sql — the watchlist a FRESH install starts with.
--
-- This is the final state the old 006 → 069 chain produced (54-ticker seed,
-- 008's extension, 009's regroup, 010/011/012 moves, 033/034 SPX in-and-out,
-- 069's 20-tag reclass). Those files used to UPDATE / soft-delete /
-- ON CONFLICT DO UPDATE the watchlist, and because the API self-migrates on
-- every boot (migrate_runner re-runs every file), they re-applied on every
-- deploy and undid operator edits (an OKLO removal came back, a DIS re-add was
-- re-removed, sector edits were reverted). Their DML was collapsed into this
-- one insert-only seed; the files keep a comment pointing here.
--
-- INSERT-ONLY: ON CONFLICT (ticker) DO NOTHING, so on an existing database
-- (prod, local) this is a no-op and the operator owns every row. Soft-deleted
-- rows are seeded with removed_at = NOW() so a fresh install keeps them as
-- removed history, exactly as the old chain did. Fresh-install parity is
-- pinned by tests/integration/storage/test_watchlist_migration_replay.py.

SET search_path TO uw_scan, public;

INSERT INTO uw_scan.watchlist (ticker, sector, sort_rank, pinned, removed_at, notes) VALUES
  -- active
  ('JPM',   'Banks',         1501, FALSE, NULL,  'Industrials / value — bank'),
  ('BAC',   'Banks',         1502, FALSE, NULL,  'Industrials / value — bank'),
  ('WFC',   'Banks',         1503, FALSE, NULL,  'Industrials / value — bank'),
  ('MS',    'Banks',         1504, FALSE, NULL,  'Industrials / value — bank'),
  ('GS',    'Banks',         1505, FALSE, NULL,  'Industrials / value — bank'),
  ('BLK',   'Banks',         1506, FALSE, NULL,  'Industrials / value — asset manager'),
  ('DIA',   'Beta',          0, FALSE, NULL,  'Dow Jones ETF'),
  ('IWM',   'Beta',          0, FALSE, NULL,  'Russell 2000 ETF'),
  ('QQQ',   'Beta',          0, FALSE, NULL,  'Nasdaq 100 ETF'),
  ('SPY',   'Beta',          0, FALSE, NULL,  'Broad market ETF'),
  ('HD',    'Consumer',      1601, FALSE, NULL,  'Industrials / value — retail'),
  ('NKE',   'Consumer',      1602, FALSE, NULL,  'Industrials / value — apparel'),
  ('SBUX',  'Consumer',      1603, FALSE, NULL,  'Industrials / value — retail'),
  ('MCD',   'Consumer',      1604, FALSE, NULL,  'Industrials / value'),
  ('COST',  'Consumer',      1605, FALSE, NULL,  'Industrials / value — retail'),
  ('KO',    'Consumer',      1606, FALSE, NULL,  'Industrials / value'),
  ('TGT',   'Consumer',      1607, FALSE, NULL,  'Industrials / value — retail'),
  ('WMT',   'Consumer',      1608, FALSE, NULL,  'Industrials / value — retail'),
  ('HYG',   'Credit',        0, FALSE, NULL,  NULL),
  ('JNK',   'Credit',        0, FALSE, NULL,  NULL),
  ('COIN',  'Crypto',        901, FALSE, NULL,  'Crypto proxy'),
  ('MSTR',  'Crypto',        902, FALSE, NULL,  'Crypto proxy — BTC treasury'),
  ('MARA',  'Crypto',        903, FALSE, NULL,  'Crypto proxy — BTC mining'),
  ('RIOT',  'Crypto',        904, FALSE, NULL,  'Crypto proxy — BTC mining'),
  ('CRCL',  'Crypto',        906, FALSE, NULL,  'Crypto proxy — USDC issuer'),
  ('AAOI',  'DC-Connect',    0, FALSE, NULL,  'Applied Optoelectronics — 800G transceivers'),
  ('ALAB',  'DC-Connect',    0, FALSE, NULL,  'Astera Labs — PCIe / silicon photonics'),
  ('ANET',  'DC-Connect',    0, FALSE, NULL,  'Semiconductor — data-center networking'),
  ('COHR',  'DC-Connect',    0, FALSE, NULL,  'Coherent — lasers, optical comms'),
  ('CRDO',  'DC-Connect',    0, FALSE, NULL,  'Semiconductor — connectivity'),
  ('FN',    'DC-Connect',    0, FALSE, NULL,  'Fabrinet — contract optical manufacturing'),
  ('GLW',   'DC-Connect',    0, FALSE, NULL,  'Semiconductor — optical fiber'),
  ('LITE',  'DC-Connect',    0, FALSE, NULL,  'Semiconductor — photonics'),
  ('MRVL',  'DC-Connect',    0, FALSE, NULL,  'Semiconductor — custom silicon'),
  ('NOK',   'DC-Connect',    0, FALSE, NULL,  'Semiconductor — telecom infra'),
  ('XOM',   'Energy',        1401, FALSE, NULL,  'Industrials / value — energy'),
  ('CVX',   'Energy',        1402, FALSE, NULL,  'Industrials / value — energy'),
  ('OXY',   'Energy',        1403, FALSE, NULL,  'Industrials / value — energy'),
  ('SOFI',  'Fintech',       1001, FALSE, NULL,  'Growth / tech — fintech'),
  ('HOOD',  'Fintech',       1002, FALSE, NULL,  'Growth / tech — fintech'),
  ('INTC',  'Foundry',       0, FALSE, NULL,  'Semiconductor'),
  ('TSEM',  'Foundry',       0, FALSE, NULL,  'Semiconductor — foundry'),
  ('TSM',   'Foundry',       0, FALSE, NULL,  'Semiconductor — foundry'),
  ('ISRG',  'Healthcare',    0, FALSE, NULL,  NULL),
  ('LLY',   'Healthcare',    1301, FALSE, NULL,  'Industrials / value — pharma'),
  ('JNJ',   'Healthcare',    1302, FALSE, NULL,  'Industrials / value — pharma'),
  ('PFE',   'Healthcare',    1304, FALSE, NULL,  'Industrials / value — pharma'),
  ('HIMS',  'Healthcare',    1306, FALSE, NULL,  'Growth / tech — telehealth'),
  ('AAPL',  'M7',            201, FALSE, NULL,  'M7'),
  ('MSFT',  'M7',            202, FALSE, NULL,  'M7'),
  ('GOOGL', 'M7',            203, FALSE, NULL,  'M7'),
  ('AMZN',  'M7',            204, FALSE, NULL,  'M7'),
  ('META',  'M7',            205, FALSE, NULL,  'M7'),
  ('TSLA',  'M7',            206, FALSE, NULL,  'M7'),
  ('NVDA',  'M7',            207, FALSE, NULL,  'M7'),
  ('GLD',   'Macro',         0, FALSE, NULL,  'Gold ETF'),
  ('SLV',   'Macro',         0, FALSE, NULL,  NULL),
  ('TLT',   'Macro',         0, FALSE, NULL,  '20Y+ Treasury ETF'),
  ('MU',    'Memory',        401, FALSE, NULL,  'Semiconductor — memory'),
  ('SNDK',  'Memory',        402, FALSE, NULL,  'Semiconductor — storage'),
  ('NBIS',  'NeoCloud',      601, FALSE, NULL,  'Semiconductor — data center'),
  ('CRWV',  'NeoCloud',      602, FALSE, NULL,  'Semiconductor — AI inference'),
  ('ORCL',  'NeoCloud',      603, FALSE, NULL,  'Mega-cap — enterprise / cloud'),
  ('IREN',  'NeoCloud',      604, FALSE, NULL,  'Semiconductor — data center / mining'),
  ('OKLO',  'Power',         651, FALSE, NULL,  'Small modular reactors — AI data center power'),
  ('BE',    'Power',         652, FALSE, NULL,  'Bloom Energy — fuel cells for AI data center power'),
  ('PLTR',  'SaaS',          701, FALSE, NULL,  'Growth / tech — data analytics'),
  ('CRM',   'SaaS',          703, FALSE, NULL,  'Mega-cap — SaaS / CRM'),
  ('SNOW',  'SaaS',          704, FALSE, NULL,  'Growth / tech — data cloud'),
  ('NET',   'SaaS',          706, FALSE, NULL,  'Growth / tech — cloud infra'),
  ('CRWD',  'SaaS',          707, FALSE, NULL,  'Growth / tech — cybersecurity'),
  ('PANW',  'SaaS',          709, FALSE, NULL,  'Growth / tech — cybersecurity'),
  ('SMH',   'Sector-ETF',    0, FALSE, NULL,  'Semiconductor ETF'),
  ('XLE',   'Sector-ETF',    0, FALSE, NULL,  'Energy sector ETF'),
  ('XLF',   'Sector-ETF',    0, FALSE, NULL,  'Financial sector ETF'),
  ('AMAT',  'Semi-Cap',      0, FALSE, NULL,  NULL),
  ('ASML',  'Semi-Cap',      0, FALSE, NULL,  'Semiconductor — lithography'),
  ('CDNS',  'Semi-Cap',      0, FALSE, NULL,  NULL),
  ('KLAC',  'Semi-Cap',      0, FALSE, NULL,  NULL),
  ('LRCX',  'Semi-Cap',      0, FALSE, NULL,  NULL),
  ('SNPS',  'Semi-Cap',      0, FALSE, NULL,  NULL),
  ('TER',   'Semi-Cap',      0, FALSE, NULL,  NULL),
  ('AMD',   'Semi-Logic',    0, FALSE, NULL,  'Semiconductor'),
  ('ARM',   'Semi-Logic',    0, FALSE, NULL,  'Semiconductor — IP licensing'),
  ('AVGO',  'Semi-Logic',    0, FALSE, NULL,  'Semiconductor'),
  ('QCOM',  'Semi-Logic',    0, FALSE, NULL,  'Semiconductor — mobile'),
  ('TXN',   'Semi-Logic',    0, FALSE, NULL,  'Semiconductor — analog'),
  ('RKLB',  'Space',         1101, FALSE, NULL,  'Growth / tech — space'),
  ('ASTS',  'Space',         1102, FALSE, NULL,  'Growth / tech — satellite'),
  ('PL',    'Space',         1103, FALSE, NULL,  'Industrials / value — satellite imaging'),
  ('BKSY',  'Space',         1104, FALSE, NULL,  'Growth / tech — geospatial'),
  ('FLY',   'Space',         1105, FALSE, NULL,  'Industrials / value — aircraft leasing'),
  -- soft-deleted (removed_at set)
  ('ABBV',  'Healthcare',    1305, FALSE, NOW(), 'Industrials / value — pharma'),
  ('ARKK',  'ETF',           110, FALSE, NOW(), 'ARK Innovation ETF'),
  ('BA',    'Defense',       1203, FALSE, NOW(), 'Industrials / value — aerospace'),
  ('CRS',   'Defense',       1204, FALSE, NOW(), 'Industrials / value — specialty alloys'),
  ('DAL',   'Airlines',      1801, FALSE, NOW(), 'Industrials / value — airline'),
  ('DDOG',  'SaaS',          705, FALSE, NOW(), 'Growth / tech — observability'),
  ('DIS',   'Telecom-Media', 1703, FALSE, NOW(), 'Industrials / value — media'),
  ('LMT',   'Defense',       1201, FALSE, NOW(), 'Industrials / value — defense'),
  ('MRK',   'Healthcare',    1303, FALSE, NOW(), 'Industrials / value — pharma'),
  ('RTX',   'Defense',       1202, FALSE, NOW(), 'Industrials / value — defense'),
  ('SMCI',  'Semiconductor', 309, FALSE, NOW(), 'Semiconductor — AI servers'),
  ('SPX',   'Index',         100, FALSE, NOW(), 'S&P 500 cash index — weekly options listed as SPXW. Cockpit ticker.'),
  ('T',     'Telecom-Media', 1701, FALSE, NOW(), 'Industrials / value — telco'),
  ('VZ',    'Telecom-Media', 1702, FALSE, NOW(), 'Industrials / value — telco'),
  ('ZS',    'SaaS',          708, FALSE, NOW(), 'Growth / tech — cybersecurity')
ON CONFLICT (ticker) DO NOTHING;
