-- 008_extend_watchlist.sql — round out the seed with another ~30 commonly-traded names.
-- Slotted into the existing sort_rank bands (M7 1-7, Semis 10-29, Growth 30-39,
-- Value/Industrials 40-59, Crypto 60-69, ETF 70-89). Idempotent.
--
-- WATCHLIST DML REMOVED (2026-10-03). This file used to INSERT ~36 more tickers
-- with pre-009 sectors. The API self-migrates on every boot, so that DML re-ran
-- on every deploy and undid operator edits to the watchlist. Its fresh-install
-- effect now lives in the insert-only final-state seed in
-- 006_seed_watchlist.sql (ON CONFLICT DO NOTHING); existing databases already
-- carry it. Data DML in a migration must be insert-only -- enforced by
-- tests/unit/storage/test_migration_dml_allowlist.py.
