-- 009_regroup_watchlist.sql
--
-- Retag `sector` on uw_scan.watchlist with thematic groupings (ETF / M7 /
-- Semiconductor / Memory / Optical / NeoCloud / SaaS / Networking / Crypto /
-- Fintech / Space / Defense / Healthcare / Energy / Banks / Consumer /
-- Telecom-Media / Airlines) and set `sort_rank` so the card grid orders
-- sections in that sequence. Adds four optical names (AAOI, COHR, FN, ALAB)
-- to the watchlist.
--
-- Convention: sort_rank = group_index * 100 + within_group_alpha_rank.
--
-- WATCHLIST DML REMOVED (2026-10-03). This file used to add AAOI/ALAB/COHR/FN
-- with ON CONFLICT DO UPDATE ... removed_at = NULL and UPDATE every ticker's
-- sector/sort_rank. The API self-migrates on every boot, so that DML re-ran on
-- every deploy and undid operator edits to the watchlist. Its fresh-install
-- effect now lives in the insert-only final-state seed in
-- 006_seed_watchlist.sql (ON CONFLICT DO NOTHING); existing databases already
-- carry it. Data DML in a migration must be insert-only -- enforced by
-- tests/unit/storage/test_migration_dml_allowlist.py.
