-- 010_orcl_oklo.sql
--
-- Move ORCL from SaaS to NeoCloud (it's increasingly an AI-infrastructure
-- story, not just enterprise SaaS), and add OKLO as a new "Nuclear/Power"
-- group sitting between NeoCloud and SaaS in the section order.
--
-- Section ordering (compatible with migration 009):
--   ETF=1, M7=2, Semi=3, Memory=4, Optical=5,
--   NeoCloud=6, Nuclear/Power=65, SaaS=7, ...
-- Using a fractional-style integer key (sort_rank in the 650 band) lets us
-- slot Nuclear/Power between NeoCloud (600s) and SaaS (700s) without
-- renumbering everything.
--
-- WATCHLIST DML REMOVED (2026-10-03). This file used to add OKLO with ON
-- CONFLICT DO UPDATE ... removed_at = NULL (un-removing an operator removal)
-- and UPDATE ORCL's sector. The API self-migrates on every boot, so that DML
-- re-ran on every deploy and undid operator edits to the watchlist. Its fresh-
-- install effect now lives in the insert-only final-state seed in
-- 006_seed_watchlist.sql (ON CONFLICT DO NOTHING); existing databases already
-- carry it. Data DML in a migration must be insert-only -- enforced by
-- tests/unit/storage/test_migration_dml_allowlist.py.
