-- 023_backfill_flow_alerts_daily_rollup.sql
-- Populate flow_alerts_daily_rollup from existing per-run flow_events.
--
-- If multiple scans exist for the same ticker + market date, keep the latest
-- run_id. This matches the stock report's latest-run behavior and avoids
-- double-counting same-day rescans.

-- REPLAYED DML REMOVED (2026-10-03). This file used to recompute every
-- flow_alerts_daily_rollup row from ALL flow_events (a full scan) and ON CONFLICT
-- DO UPDATE over the runtime writer's values, with a hard-coded 100 alert limit
-- where the writer uses alert_limit. The API self-migrates on every boot, so that
-- rewrite re-ran on every deploy. The one-time backfill was already applied: on
-- prod 2026-10-03 the rollup spans 2026-04-13 (the first flow_events row) to
-- 2026-10-02, and the runtime writer maintains it. A fresh install has no
-- flow_events, so the backfill was a no-op there. Data DML in a migration must be
-- insert-only -- enforced by tests/unit/storage/test_migration_dml_allowlist.py.
