-- 048_gold_cb_flow_replay_invalidation.sql — invalidate CB level-sum posture rows.
-- A short-lived bug summed CB reserve levels as a 12m flow after WGC data was
-- populated. Keep audit rows, but make replay prefer rows recomputed from
-- country-level net changes.

-- REPLAYED DML REMOVED (2026-10-03). Two UPDATEs here used to invalidate posture
-- rows whose CB 12m fields held summed levels, and earlier same-day rows lacking
-- CB fields. The API self-migrates on every boot, so they re-ran on every deploy
-- against rows written later, which changed which row fetch_gold_posture_as_of
-- (computed_at ASC) returns. The one-time effect was already applied: on prod
-- 2026-10-03 both predicates matched 0 rows (4 rows were invalidated in 2026-05).
-- A fresh install has no rows. Data DML in a migration must be insert-only --
-- enforced by tests/unit/storage/test_migration_dml_allowlist.py.
