-- 069_reclass_watchlist_20tags.sql
--
-- Reclassifies uw_scan.watchlist into the 20-tag taxonomy:
--   Index:     Beta, Sector-ETF, Credit, Macro
--   AI/Tech:   M7, Foundry, Semi-Logic, Semi-Cap, Memory, DC-Connect,
--              NeoCloud, Power, SaaS
--   Thematic:  Crypto, Fintech, Space
--   Defensive: Healthcare, Energy, Banks, Consumer
--
-- (It claimed "idempotent, safe to re-run" -- true for the schema, false for
-- operator edits made after it ran; see below.)
--
-- WATCHLIST DML REMOVED (2026-10-03). This file used to soft-delete 15 tickers,
-- UPDATE sectors into the 20-tag taxonomy, and add 10 tickers with ON CONFLICT
-- DO UPDATE ... removed_at = NULL. The API self-migrates on every boot, so that
-- DML re-ran on every deploy and undid operator edits to the watchlist. Its
-- fresh-install effect now lives in the insert-only final-state seed in
-- 006_seed_watchlist.sql (ON CONFLICT DO NOTHING); existing databases already
-- carry it. Data DML in a migration must be insert-only -- enforced by
-- tests/unit/storage/test_migration_dml_allowlist.py.
