-- 076_skew_verdict_drop_regime.sql — regime leaves the directional verdict bucket key.
--
-- With ~13 months of backfill, keying buckets on regime (a coin-flip SPY-RV split)
-- fragmented the sample so few buckets ever cleared n>=20 — the directional engine
-- produced no verdicts at all. Regime robustness now lives in the quarterly
-- catastrophic-degradation gate (full history); the canonical CRI level becomes the
-- live regime *tag*, not a backtest slicer. New bucket key:
-- (asset_class, deviation_class, drive_class).
--
-- Verdicts are fully derived (regenerated by run_skew_markout), so dropping the column
-- + re-keying loses nothing recomputable. The whole transition is guarded by the
-- column-exists check: it fires once on the old schema, then a re-run of migrate.sh is
-- a pure no-op and never wipes freshly-computed verdicts.

SET search_path TO uw_scan, public;

DO $$ BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'uw_scan'
      AND table_name = 'skew_directional_verdicts'
      AND column_name = 'regime'
  ) THEN
    ALTER TABLE uw_scan.skew_directional_verdicts
      DROP CONSTRAINT IF EXISTS skew_directional_verdicts_pkey;
    DELETE FROM uw_scan.skew_directional_verdicts;  -- stale under the new key; markout repopulates
    ALTER TABLE uw_scan.skew_directional_verdicts DROP COLUMN regime;
    ALTER TABLE uw_scan.skew_directional_verdicts
      ADD PRIMARY KEY (asset_class, deviation_class, drive_class);
  END IF;
END $$;
