"""Watchlist seed migrations: fresh-install parity + replay safety.

The API self-migrates on every boot (``migrate_runner`` re-runs EVERY file), so a
migration that UPDATEs / soft-deletes / ``ON CONFLICT DO UPDATE``s the watchlist
re-applies on every deploy and silently undoes operator edits (an OKLO removal
came back, a DIS re-add was re-removed). The fix collapsed the watchlist DML of
006-069 into one insert-only final-state seed in ``006_seed_watchlist.sql``.

(a) A fresh install must produce exactly the watchlist the ORIGINAL chain
    produced. The golden fixture was generated by running origin/main ea69039e's
    migrations into an empty schema:

        git archive ea69039e src/uw_scan/storage/migrations | tar -x -C <dir>
        UW_SCAN_TEST_DB_NAME=<scratch test db> ... \\
          uv run python tests/integration/storage/test_watchlist_migration_replay.py \\
          <dir>/src/uw_scan/storage/migrations

    Timestamps are excluded; ``removed_at`` is compared by NULL-ness only.
(b) Operator edits survive a full replay.
(c) Replaying twice yields identical state (timestamps included).
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path
from typing import Any

import psycopg
import pytest

from uw_scan.storage.migrate_runner import MIGRATIONS_DIR, apply_migrations

pytestmark = pytest.mark.integration

GOLDEN = Path(__file__).parent / "fixtures" / "watchlist_fresh_install_golden.json"
_TIMESTAMP_COLS = ("added_at", "removed_at")


def _snapshot(conn: psycopg.Connection) -> list[dict[str, Any]]:
    """Every watchlist column except timestamps, plus ``removed`` (bool)."""
    with conn.cursor() as cur:
        cur.execute(
            "SELECT column_name FROM information_schema.columns "
            "WHERE table_schema = 'uw_scan' AND table_name = 'watchlist' "
            "ORDER BY column_name"
        )
        cols = [r[0] for r in cur.fetchall() if r[0] not in _TIMESTAMP_COLS]
        select = ", ".join(cols)
        cur.execute(
            f"SELECT {select}, removed_at IS NOT NULL AS removed "
            "FROM uw_scan.watchlist ORDER BY ticker"
        )
        names = [*cols, "removed"]
        return [dict(zip(names, row, strict=True)) for row in cur.fetchall()]


def _full_dump(conn: psycopg.Connection) -> list[tuple]:
    with conn.cursor() as cur:
        cur.execute("SELECT * FROM uw_scan.watchlist ORDER BY ticker")
        return cur.fetchall()


def _replay(fixture_conn: psycopg.Connection, dsn: str) -> None:
    """Re-run every migration, as an API boot does.

    The fixture connection is ended first: an idle-in-transaction session holds
    locks that ``ALTER TABLE`` / ``CREATE INDEX CONCURRENTLY`` would wait on forever.
    """
    fixture_conn.rollback()
    with psycopg.connect(dsn, autocommit=True) as conn:
        apply_migrations(conn, log=lambda _msg: None)


def test_fresh_install_matches_original_chain(seeded_db_empty_cards):
    golden = json.loads(GOLDEN.read_text())
    assert _snapshot(seeded_db_empty_cards.conn) == golden


def test_operator_edits_survive_replay(seeded_db_empty_cards, _migrated_settings):
    repo = seeded_db_empty_cards
    conn = repo.conn
    # Preconditions — these are exactly the rows the old migrations fought over.
    rows = {r["ticker"]: r for r in _snapshot(conn)}
    assert rows["OKLO"]["removed"] is False
    assert rows["DIS"]["removed"] is True
    assert rows["IREN"]["sector"] == "NeoCloud"

    repo.soft_delete_watchlist_ticker("OKLO")
    repo.add_watchlist_ticker(ticker="DIS", sector="Consumer")
    repo.patch_watchlist_ticker("IREN", sector="Crypto")
    conn.commit()
    edited = _full_dump(conn)

    _replay(conn, _migrated_settings.db_dsn())

    after = {r["ticker"]: r for r in _snapshot(conn)}
    assert after["OKLO"]["removed"] is True
    assert after["DIS"]["removed"] is False
    assert after["DIS"]["sector"] == "Consumer"
    assert after["IREN"]["sector"] == "Crypto"
    assert _full_dump(conn) == edited


def test_replay_is_idempotent(seeded_db_empty_cards, _migrated_settings):
    conn = seeded_db_empty_cards.conn
    fresh = _full_dump(conn)
    _replay(conn, _migrated_settings.db_dsn())
    first = _full_dump(conn)
    _replay(conn, _migrated_settings.db_dsn())
    assert _full_dump(conn) == first == fresh


def _write_golden(migrations_dir: Path) -> None:
    """Regenerate the golden by migrating an EMPTY schema in the test DB."""
    from uw_scan.config import Settings

    db_name = os.environ["UW_SCAN_TEST_DB_NAME"]
    settings = Settings.from_env().model_copy(update={"db_name": db_name})
    with psycopg.connect(settings.db_dsn(), autocommit=True) as conn:
        conn.execute("DROP SCHEMA IF EXISTS uw_scan CASCADE")
        conn.execute("CREATE SCHEMA uw_scan")
        apply_migrations(conn, migrations_dir=migrations_dir, log=lambda _msg: None)
        snap = _snapshot(conn)
    GOLDEN.write_text(json.dumps(snap, indent=1, ensure_ascii=False) + "\n")
    print(f"wrote {len(snap)} rows to {GOLDEN}")


if __name__ == "__main__":
    _write_golden(Path(sys.argv[1]) if len(sys.argv) > 1 else MIGRATIONS_DIR)
