#!/usr/bin/env python
"""One-off materializer for the chanlun trust probe's frozen universe.

Source: UW stock screener, top ~250 by market cap (order=marketcap desc,
issue_types = Common Stock / ADR / ETF), pulled 2026-07-18. Kept for
reproducibility — the committed artifact is universe.csv, not this script.

Filter: keep only tickers apex serves >=700 clean daily bars for (~3y of
sessions), which drops newly-listed / data-gap names and any ticker-format
mismatch (apex 404 -> [] -> dropped). Never fabricate a ticker.

Reproduce: uv run python scripts/research/_chanlun_trust_universe.py
"""

from __future__ import annotations

from datetime import date, timedelta
from pathlib import Path

from uw_scan.sources.apex import fetch_bars

# Top ~250 by market cap from the UW screener (as_of 2026-07-18).
CANDIDATES = [
    "NVDA",
    "AAPL",
    "MSFT",
    "AMZN",
    "TSM",
    "GOOGL",
    "GOOG",
    "AVGO",
    "SPCX",
    "TSLA",
    "META",
    "SKHY",
    "LLY",
    "MU",
    "JPM",
    "WMT",
    "IVV",
    "AMD",
    "ASML",
    "V",
    "XOM",
    "JNJ",
    "BRKB",
    "VOO",
    "INTC",
    "MA",
    "QQQ",
    "ONC",
    "ABBV",
    "AMAT",
    "BAC",
    "CSCO",
    "VTI",
    "COST",
    "CAT",
    "LRCX",
    "UNH",
    "CVX",
    "KO",
    "GE",
    "ORCL",
    "PG",
    "HD",
    "HSBC",
    "MS",
    "GS",
    "MRK",
    "NFLX",
    "PLTR",
    "RY",
    "PM",
    "NVS",
    "PANW",
    "KLAC",
    "ARM",
    "GEV",
    "WFC",
    "TXN",
    "MUFG",
    "AZN",
    "RTX",
    "FMX",
    "AXP",
    "SHEL",
    "LIN",
    "TM",
    "C",
    "ANET",
    "TD",
    "SNDK",
    "TMUS",
    "DEO",
    "CRWD",
    "IBM",
    "BHP",
    "TMO",
    "AMGN",
    "SAN",
    "SAP",
    "MCD",
    "PEP",
    "CX",
    "APH",
    "IEFA",
    "NEE",
    "ADI",
    "VZ",
    "QCOM",
    "SCHW",
    "UBS",
    "UNP",
    "TTE",
    "DIS",
    "ABT",
    "TJX",
    "WELL",
    "GILD",
    "BA",
    "BLK",
    "STX",
    "MRVL",
    "DE",
    "WDC",
    "ETN",
    "T",
    "SHOP",
    "IEMG",
    "E",
    "UBER",
    "BBVA",
    "SCCO",
    "BUD",
    "BTI",
    "DHR",
    "HON",
    "PFE",
    "BKNG",
    "ISRG",
    "CRM",
    "VEA",
    "PLD",
    "COP",
    "UL",
    "GLW",
    "CVS",
    "VUG",
    "SPGI",
    "HDB",
    "CB",
    "APP",
    "COF",
    "BMO",
    "AGG",
    "DELL",
    "SYK",
    "SONY",
    "VTV",
    "IWF",
    "BMY",
    "SBUX",
    "PDD",
    "VRTX",
    "ENB",
    "IJH",
    "MO",
    "LOW",
    "PH",
    "PGR",
    "LMT",
    "FTNT",
    "RIO",
    "GSK",
    "VRT",
    "BND",
    "HMC",
    "CM",
    "BNS",
    "BNY",
    "IJR",
    "HWM",
    "SO",
    "NOW",
    "MDT",
    "TT",
    "IBN",
    "ADP",
    "PNC",
    "MCK",
    "CDNS",
    "GD",
    "EQIX",
    "USB",
    "SMFG",
    "SGOV",
    "DUK",
    "SPOT",
    "MAR",
    "BCS",
    "MNST",
    "WM",
    "NEM",
    "RSP",
    "ACN",
    "STRF",
    "BX",
    "ING",
    "ITOT",
    "PWR",
    "CSX",
    "FDX",
    "MELI",
    "STRD",
    "SNOW",
    "ADBE",
    "BP",
    "KKR",
    "WMB",
    "CEG",
    "MCO",
    "CMI",
    "MPC",
    "CME",
    "CNQ",
    "VLO",
    "EQNR",
    "TX",
    "ASX",
    "MRSH",
    "UPS",
    "NET",
    "DDOG",
    "LYG",
    "JCI",
    "CMCSA",
    "NGG",
    "HCA",
    "VIG",
    "ATMP",
    "MMM",
    "FCX",
    "HOOD",
    "SHW",
    "NTES",
    "BN",
    "CTAS",
    "CP",
    "IWD",
    "EPD",
    "IWM",
    "ITW",
    "ELV",
    "PSX",
    "INTU",
    "ICE",
    "SNPS",
    "BAM",
    "VWO",
    "MDLZ",
    "RCL",
    "CNI",
    "AMX",
    "AON",
    "AMT",
    "HONA",
    "EDU",
    "EMR",
    "ECL",
    "EFA",
    "DASH",
    "VXUS",
]

OUT = Path("docs/research/2026-07-18-chanlun-trust-silver/universe.csv")
AS_OF = date.today().isoformat()
MIN_BARS = 700  # ~3y of sessions
START = date.today() - timedelta(days=int(3.2 * 365))


def main() -> None:
    kept: list[str] = []
    for t in CANDIDATES:
        bars = fetch_bars(t, "1d", START, limit=0)
        if len(bars) >= MIN_BARS:
            kept.append(t)
        else:
            print(f"  drop {t}: {len(bars)} bars")
    print(f"kept {len(kept)}/{len(CANDIDATES)}")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w") as f:
        f.write("ticker,as_of\n")
        for t in kept:
            f.write(f"{t},{AS_OF}\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
